/** Centralised TanStack Query key factory.
 *  Use spread to build full keys: [...QUERY_KEYS.trading.performance, params]
 */
export const QUERY_KEYS = {
  market: {
    quotesLive:     ['market', 'quotes-live']       as const,
    quotesSnapshot: ['market', 'quotes-snapshot']   as const,
    systemMessages: ['market', 'system-messages']   as const,
    benchmark:      (symbol: string) => ['market', 'benchmark', symbol] as const,
  },
  trading: {
    performance:    ['trading', 'performance']       as const,
    executions:     ['trading', 'executions']        as const,
    executionsBook: ['trading', 'executions-book']   as const,
    optStockLinks:  ['trading', 'opt-stock-links']   as const,
    transactions:   ['trading', 'transactions']      as const,
  },
  monitor: {
    status:         ['monitor', 'status']            as const,
    openOrders:     ['monitor', 'open-orders']       as const,
    heartbeat:      ['monitor', 'heartbeat']         as const,
    operations:     ['monitor', 'operations']        as const,
  },
  portfolio: {
    accounts:              ['portfolio', 'accounts']              as const,
    positions:             ['portfolio', 'positions']             as const,
    modelAnalysis:         ['portfolio', 'model-analysis']        as const,
    positionCategories:    ['portfolio', 'position-categories']   as const,
    marketStreamsSymbolOrder: ['portfolio', 'market-streams-symbol-order'] as const,
  },
  research: {
    greeks:         ['research', 'greeks']           as const,
    screener:       ['research', 'screener']         as const,
    stockData:      ['research', 'stock-data']       as const,
    watchlist:      ['research', 'watchlist']        as const,
    performanceKelly: ['research', 'performance-kelly'] as const,
    stockDataReadiness: {
      summary:       ['research', 'stock-data-readiness', 'summary'] as const,
      criteriaStats: ['research', 'stock-data-readiness', 'criteria-stats'] as const,
    },
    celeryBeat:     ['research', 'celery-beat']      as const,
    stockScreener: {
      criteriaStats:    ['research', 'stock-screener', 'criteria-stats'] as const,
      fundDistSymbols:  (n: number) => ['research', 'stock-screener', 'fund-dist', n] as const,
      techDistSymbols:  (n: number) => ['research', 'stock-screener', 'tech-dist', n] as const,
      readinessSnapshot: (key: string) => ['research', 'stock-screener', 'snapshot', key] as const,
    },
    stockInspector: (symbol: string) => ['research', 'stock-inspector', symbol] as const,
    tickerOverview:   (symbol: string) => ['research', 'ticker-overview', symbol] as const,
    fundConditions:   (symbol: string) => ['research', 'fundamental-conditions', symbol] as const,
    techConditions:   (symbol: string) => ['research', 'technical-conditions', symbol] as const,
    fundRaw:          (symbol: string) => ['research', 'fund-raw', symbol] as const,
    statements:       (symbol: string) => ['research', 'statements', symbol] as const,
    optionPcr:        (symbol: string) => ['research', 'option-pcr', symbol] as const,
    barStats:         (symbol: string) => ['market', 'bar-stats', symbol] as const,
    discovery: {
      expirations:    ['research', 'discovery', 'expirations']    as const,
      snapshots:      ['research', 'discovery', 'snapshots']      as const,
      ivTerm:         ['research', 'discovery', 'iv-term']        as const,
      maxPain:        ['research', 'discovery', 'max-pain']       as const,
      greeksCoverage: ['research', 'discovery', 'greeks-coverage'] as const,
      massiveStatus:  ['research', 'discovery', 'massive-status']  as const,
      dailyChecklist: ['research', 'discovery', 'daily-checklist'] as const,
    },
  },
  strategy: {
    instances:      ['strategy', 'instances']        as const,
    instanceDetail: ['strategy', 'instance-detail']  as const,
    opportunities:  ['strategy', 'opportunities']    as const,
    structures:     ['strategy', 'structures']       as const,
    structureDetail:['strategy', 'structure-detail'] as const,
    history:        ['strategy', 'history']          as const,
    gates:          ['strategy', 'gates']            as const,
    gateSafety:     ['strategy', 'gate-safety']      as const,
    allocations:    ['strategy', 'allocations']      as const,
    winRate:        ['strategy', 'win-rate']         as const,
  },
  settings: {
    apiHealth:        ['settings', 'api-health']        as const,
    apiHealthMassive: ['settings', 'api-health', 'massive-status'] as const,
  },
  ops: {
    workers:            ['ops', 'workers']                   as const,
    queuesSummary:      ['ops', 'queues-summary']            as const,
    workerProfiles:     ['ops', 'worker-profiles']           as const,
    workerInstances:    ['ops', 'worker-instances']          as const,
    celeryCapabilities: ['ops', 'celery-capabilities']       as const,
    aggregatedJobs:     ['ops', 'aggregated-jobs']           as const,
    brokerStatus:       ['ops', 'broker-status']             as const,
    audit:              ['ops', 'audit']                     as const,
    celery:             ['ops', 'celery']                    as const,
    daemon:             ['ops', 'daemon']                    as const,
    massiveJobs:        ['ops', 'massive-jobs']              as const,
    barsJobs:           ['ops', 'bars-jobs']                 as const,
    // Socket / market ingest services
    ingestServices:     ['ops', 'ingest-services']           as const,
    opsHealth:          ['ops', 'ops-health']                as const,
    capabilities:       ['ops', 'capabilities']              as const,
  },
} as const
