import { z } from 'zod'

const passCountBucketSchema = z.object({
  conditions_passed: z.number(),
  symbol_count: z.number(),
})

const conditionStatSchema = z.object({
  id: z.string(),
  label: z.string(),
  pass: z.number(),
  fail: z.number(),
})

export const SepaCriteriaStatsSchema = z.object({
  ok: z.boolean(),
  error: z.string().optional(),
  universe_count: z.number(),
  computed_at: z.string(),
  fundamental: z.object({
    cached_count: z.number(),
    fund_pass_count: z.number(),
    no_data_count: z.number(),
    pass_6_plus: z.number().optional(),
    pass_4_plus: z.number().optional(),
    eval_date: z.string().optional(),
    conditions: z.array(conditionStatSchema),
    pass_count_distribution: z.array(passCountBucketSchema).optional(),
  }),
  technical: z.object({
    total_in_snapshot: z.number(),
    price_ready_count: z.number(),
    fund_cached_count: z.number(),
    both_ready: z.number(),
    bars_ge_252: z.number(),
    bars_ge_240: z.number(),
    bars_ge_200: z.number(),
    bars_lt_200: z.number(),
    no_bars: z.number(),
    failure_reasons: z.array(z.object({ notes: z.string().nullable(), cnt: z.number() })),
    tech_cached_count: z.number(),
    tech_pass_count: z.number(),
    tech_insufficient_count: z.number(),
    pass_8_plus: z.number().optional(),
    pass_4_plus: z.number().optional(),
    eval_date: z.string().optional(),
    conditions: z.array(conditionStatSchema),
    pass_count_distribution: z.array(passCountBucketSchema).optional(),
  }),
})

export const ReadinessSnapshotRowSchema = z.object({
  symbol: z.string(),
  found: z.boolean(),
  as_of_date: z.string().nullable().optional(),
  included_in_universe: z.boolean().optional(),
  price_ready: z.boolean().optional(),
  bar_count_lookback: z.number().optional(),
  income_stmt_ready: z.boolean().optional(),
  income_stmt_q_count: z.number().optional(),
  income_stmt_a_count: z.number().optional(),
  balance_sheet_present: z.boolean().optional(),
  cash_flow_present: z.boolean().optional(),
  ratios_present: z.boolean().optional(),
  short_interest_present: z.boolean().optional(),
  short_volume_present: z.boolean().optional(),
  fundamental_pass_count: z.number().optional(),
  fundamental_insufficient: z.boolean().optional(),
  passed_conditions: z.array(z.string()).optional(),
  technical_pass: z.boolean().optional(),
  technical_pass_count: z.number().optional(),
  technical_insufficient: z.boolean().optional(),
  passed_tech_conditions: z.array(z.string()).optional(),
  // Analytics flat columns (new format — all optional for backward compat)
  eval_date: z.string().optional(),
  overall_rank: z.number().optional(),
  decile: z.number().optional(),
  composite_score: z.number().optional(),
  fund_pass_count: z.number().optional(),
  fund_insufficient: z.boolean().optional(),
  eps_q2q_ge_25pct: z.boolean().optional(),
  rev_q2q_ge_25pct: z.boolean().optional(),
  eps_acc_2q: z.boolean().optional(),
  rev_acc_2q: z.boolean().optional(),
  eps_3y_ge_15pct: z.boolean().optional(),
  rev_3y_ge_15pct: z.boolean().optional(),
  eps_acc_fy: z.boolean().optional(),
  rev_acc_fy: z.boolean().optional(),
  tech_pass_count: z.number().optional(),
  avg_volume_50_gt_threshold: z.boolean().optional(),
  close_ge_low52_x_1_3: z.boolean().optional(),
  close_ge_high52_x_0_75: z.boolean().optional(),
  sma50_gt_sma150: z.boolean().optional(),
  sma50_gt_sma200: z.boolean().optional(),
  sma150_gt_sma200: z.boolean().optional(),
  sma200_rising_1m: z.boolean().optional(),
  price_gt_sma50: z.boolean().optional(),
  price_gt_sma150: z.boolean().optional(),
  price_gt_sma200: z.boolean().optional(),
  crs_ge_70: z.boolean().optional(),
  eps_q0: z.number().nullable().optional(),
  eps_g0: z.number().nullable().optional(),
  rev_q0: z.number().nullable().optional(),
  rev_g0: z.number().nullable().optional(),
  latest_close: z.number().nullable().optional(),
  sma_50: z.number().nullable().optional(),
  sma_150: z.number().nullable().optional(),
  sma_200: z.number().nullable().optional(),
  crs_percentile: z.number().nullable().optional(),
  momentum_score: z.number().nullable().optional(),
  structure_score: z.number().nullable().optional(),
  sentiment_score: z.number().nullable().optional(),
  company_name: z.string().optional(),
  primary_exchange: z.string().optional(),
})

export const SymbolsReadinessSnapshotSchema = z.object({
  ok: z.boolean(),
  error: z.string().optional(),
  as_of_date: z.string().nullable().optional(),
  count: z.number().optional(),
  symbols: z.array(ReadinessSnapshotRowSchema).optional(),
})
