/**
 * Design-walk notes · Research › Pipeline (Discover and Analyze).
 *
 * The stations a reading passes through before it becomes a candidate: the two
 * ratings pages, the two screens, and the Symbol page they all open into.
 *
 * Split out of `research.ts` on 2026-09-21, when the Vol ratings walk pushed
 * that file past the 800-line ratchet. The seam is the one the menu already
 * draws — Pipeline's own rows on one side, the loop and the Copilot that
 * consume them on the other — so a reader looking for a note knows which file
 * without opening both.
 */
export const RESEARCH_PIPELINE_NOTES: Record<string, string> = {
  '/research/explorer':
    'Walked 2026-09-22. This page has no prototype of its own to walk against: the design registry maps /research/explorer to Research Screener.dc.html, and that prototype is already built and signed at /research/screener — the two registry rows are one design page under two addresses, and reading the prototype settles which. Research Screener.dc.html is universe → criteria stages → results → lineage; Explorer has no criteria of its own. It is a tab shell over four things, and the walk’s job was to say where each one goes and to fix what the page itself gets wrong. Where the four go, measured rather than assumed. SEPA: its destination is Stock ratings, and that is verified at the data level rather than claimed — both pages call fetchSepaDaily, and the ratings table’s four lenses (Trend · Growth · Momentum · Structure) are the same SEPA reading reorganised as a weighted composite. Momentum: the score has a home on Stock ratings, and the rest of the radar does not. /research/momentum/radar carries a grade (A+–D), a path (EXT) and eight named sub-factors with their own notes — z_sdt, z_v, accept_vwap, z_ofi, h_52w, o_plus, a_factor, r_sec, crash — while Stock ratings’ Momentum column is SEPA’s own momentum_score on a 0–100 scale. Grade, path and the eight are **to be confirmed**, not lost. Events: the ruling of 2026-09-20 recorded that this tab moved to Home as Alerts, and the Alerts walk of 2026-09-22 corrected it — only the alerts half moved. The events board itself (table, theme aggregates, forward calendar) renders here and nowhere else, and Alerts’ own header links back to it. All four of its stores answer zero rows on DEV, so what is owed is a destination for an empty capability, which is the Owner’s call. Rules: a landing card, and its two links work — /research/stock-screener is a redirect to the design’s Stock screen, /research/loop/candidates is the Candidate Pool. Two defects were fixed on the page itself, both found by the sweep. Neither tab had a single link: SEPA drew 200 names across its two faces and Momentum 100 cards, and not one of them went anywhere. A ticker is its own destination, so all 310 open the Dossier now. And the Momentum grid was quietly dishonest about time: GET /research/momentum/radar returns the top 100 scores over its whole history sorted by score, not one row per symbol on the latest session — on DEV that is 02JUL26 to 21SEP26 with only 13 rows from the newest day and 24 symbols appearing more than once (PLTR at 85 on 04AUG and 81 on 07AUG). The grid carried no date at all, so a six-week-old grade read as today’s opinion. Each card now carries the session it was scored on, the grid says what window is in view, and the React key carries the date too — the duplicates had been colliding on symbol alone. State: **moving**, the same as the two tab pages it shells (Owner ruling 2026-09-20), with the events board’s destination as the one open question. Absence from the design is not deletion; nothing here was removed.',
  '/research/signal-decay':
    'Walked 2026-09-22 against Research Signal Decay.dc.html at Rev 2026-09-17.1, rendered side by side with the app on local DEV (:5173). The page was a per-lens instrument — pick a lens, a window and a regime and read that one signal’s hot/cold matrix, its intersections and its symbols — and the design’s page asks a question no amount of picking one at a time answers: which of them is slipping. So the design’s roster leads and the instrument stays below it under One lens, up close. Built: the Signals roster (12 rows, worst drift first), the amber Decay alerts panel above it, the design’s header line and its Playbook stats →, and the footer that carries the page’s whole argument. The rule, in the design’s own words: decay is judged against each signal’s own 1-year average, not against other signals — a 55% signal drifting to 40% is decaying, a 45% signal holding 45% is not. The endpoint takes a window_days, so now and its own year are the same call asked twice, 90 against 252. Measured on DEV 2026-09-22 for vrp hot: 40.1% on 152 settled at 90 days against 43.7% on 245 at 252, which is a −3.6-point drift. The page proves its own rule on the live data: Gamma · cold reads 38% and is not decaying, because 38% is eight points above its own year. The unit is a lens side, not a named strategy. The design’s signals are written prose (IV rank ≥ 60 short vol, 25Δ RR reversal); this side’s registry has six decay lenses and each fires hot or cold, which is the thing the engine measures a hit rate for — so a row is IV Rank · hot, named as the engine names it rather than dressed up to look like the design’s. Twelve rows, from six lenses asked twice. Thin samples are the design’s rule and this side already had the number: THIN_SAMPLE = 10 in symbolRecord.ts is exactly the design’s grey month is n < 10, not a bad month, so the sparkline greys a week under it and a drift is never called a decay on fewer than ten settled outcomes. Five of the twelve rows currently read nothing has settled at 20 days yet — the window has not closed — which is a fact about the horizon, not a zero. Owed, named in the footer rather than drawn empty: Profit factor. The response carries hit rates and no payoff, so there is no field to read and a PF column would be a claim the engine cannot make; the design’s second alert condition (PF < 1.2) goes with it, so an alert here fires on drift alone and the footer says so. Diverged, each with its reason. The 6-month trend bars are the engine’s weekly 5-day rolling rate — the only series it keeps — so the column is labelled for what it is rather than letting a 20-day header sit over a 5-day chart; the design’s months become 26 weeks, which is the same six months in the unit the data has. The design’s alert line says it zeroes the conviction cap in Compare; Compare has no page on this side, so the panel names where the credit would flow instead of linking into nothing. Extracted before duplicating (§14.2): pct(0–1 rate → whole percent) existed three times — in this page, in bookExplanations and in the roster this walk added — and fmtPctFromFraction(v, 0) in lib/format.ts was already exactly it. All three now call the shared one; the ratchet caught the fourth copy the moment it was written.',
  '/research/contract-screener':
    'Walked 2026-09-22 against Research Contract Screener.dc.html at Rev 2026-09-19.2, rendered side by side with the app on local DEV (:5173). The design’s own description places this page third — Stock Explorer picks companies, Option Scan picks underlyings with premium, this picks the contracts that fit a structure — and the page had no first step at all: it opened on an empty textarea, asking the reader to retype a list three other pages already hold. It also had no funnel, which is the design’s one device for the thing this page does most, which is return nothing. Built: the four-cell funnel strip; 1 · Underlyings with the design’s source buttons and droppable symbol chips; the numbered rail around 2 · Structure and 3 · Filters; the design’s header line; and an empty state that points at the funnel instead of shrugging. The finding of this walk is that the engine is dark, and it is measured rather than inferred. POST /research/screener answers ok:true with total_contracts:0 for every symbol tried — including ANET, which the market-data plugin’s own coverage reports as 2,150 option contracts across 21 expiries, newest stamped the same morning. It answers the same at every source value (massive, ib, polygon, chain, snapshot and omitted) and with the filters opened to their widest: DTE 7–120, P(ITM) ≤ 90%, return ≥ 0, spread ≤ 50%, premium ≥ 0, earnings allowed. The engine gives the same reason each time — No snapshot data, run Market Data Plugin sync first — so the emptiness is neither the filters nor the symbols: the screener reads an option snapshot store that the plugin’s contract coverage does not fill. The contracts table is therefore deliberately not rebuilt. It cannot be checked against a single row, and reshaping a table against a design without ever seeing it hold data is the walk failing quietly. What is built is the half that makes a dark engine legible: the funnel names the stage that emptied and carries the engine’s own sentence for it, which is exactly the job the design gives it. Three of the design’s four sources exist and are measured: Option Scan · IV-rich today reads the scan’s own lens_flags.iv_rank, and hot is its word — 121 of the 500 it ranks; Watchlist holds 22; In the book is the 11 watchlist rows the importer filed from positions, which is where this app records that a name is held. The fourth, Stock Explorer · a saved screen, has no store — nothing on this side saves a screen — and is drawn disabled with that reason rather than left out, because a picker with three options where the design has four reads as a smaller idea rather than a missing one. A source is capped at three names, and the cap is measured, not chosen: two names answer in 15s, three in 31s, and five and eleven both exceed the client’s own 60-second abort and show a timeout instead of a result — roughly ten seconds a name. A button that fills the box with 121 names and then always times out is worse than one that takes three and says so, which the panel does, once, under the list. Diverged, with its reason: the Run button stays, against the design’s live — no Run button. At ten seconds a name a live re-run would fire a half-minute request per slider drag; the design’s phrase describes a prototype that computes its chain in the browser. Structure: the design enables cash-secured put and covered call and refuses the two spreads; this side enables only the put, and the three refused are drawn and disabled with the reason — the spread structures need two legs priced together, which the engine does not do — because a structure missing from the picker reads as a structure nobody trades. Not built, and owed rather than missing: the contracts table’s own columns (Rule, Cash/ct, the ⇄ Compare and ◫ Discovery and ＋ Plan row actions) and Save as rule → from the filters. Each needs rows to be built against, and the page has none to show; the per-symbol Save-as-Opportunity this side already had is untouched and still reaches the same store.',
  '/research/symbol':
    'Walked 2026-09-14 against Research Symbol.dc.html (REDO); my legs, since-you-looked, Plan this and the Structure panel built. Owner signed off on STG 2026-09-15. Re-stamped on Rev 2026-09-15.5 (no construction change to the page). Re-stamped on Rev 2026-09-17.1 (§14.7 colours only: green / red direction, unrealized orange, applied in e05dce2); Owner re-signed after the colour look 2026-09-17. Rev 2026-09-18.2 replaces the header keys with the six verbs, adds the Your verdict panel and seats you · hand verdicts in the Record table, so the sign-off reads stale; the verdict panel and record row are W2, the verbs W3.'
    + ' '
    + 'RE-WALKED 2026-09-21 against Rev 2026-09-18.2, prototype beside the app at one viewport. The '
    + 'first thing the comparison said was about the top of the page: the design opens with the name '
    + '\u2014 `PLTR \u00b7 156.90` and one line of verdict over `3 of 8 lenses decisive` \u2014 and this side opened '
    + 'with the word \u00abSymbol\u00bb and a chip strip. The page said what it was, not what it had concluded '
    + 'about the name in it. **`SymbolIdentity` is that line**: ticker (linking to the name in the '
    + 'book), last price, the decisive lenses in their own words, and the count. '
    + 'Three things it deliberately does not print, each measured: the **company name** is in none of '
    + 'this app\u2019s market payloads; the **change %** cannot be computed because the quote carries '
    + 'bid/ask/last/mid and no previous close, so the figure says `last` and stops; and the design\u2019s '
    + 'one synthesised sentence (\u00abSell premium bias\u00bb) is not synthesised here \u2014 nothing on this side '
    + 'composes lenses into a stance, and writing one would put a judgement in the app\u2019s mouth that no '
    + 'lens made. The decisive lenses are listed instead. '
    + 'THE RIGHT RAIL, item by item. **Since last snapshot** is already here as a strip under the '
    + 'header (`SymbolSinceSnapshot`). **Record on this symbol** is already here as the Validation '
    + 'face, which says which lenses have a settled record on this name and which read all symbols \u2014 '
    + 'the same reading, in a face rather than a rail. **Your verdict** is blocked and measured: '
    + '`/research/symbol-verdicts` answers 404, there is no verdict store, and that is the same hole '
    + 'the Pipeline census recorded as `symbol_verdict` owed. Recording a verdict is also what the '
    + 'deferred six verbs would settle, so both wait on one thing. '
    + 'The prototype\u2019s seventh tab, **Payoff**, is not missing: an earlier round folded it onto the '
    + 'Chain tab\u2019s structure panel, which reuses the portfolio risk-profile engine rather than '
    + 'standing up a second payoff maths. That decision stands and is named here so the tab count '
    + 'difference is not read as a gap. '
    + 'SECOND PASS the same day, on the Owner\u2019s read (\u300c\u548c Design \u7684\u8bbe\u8ba1\u5dee\u8ddd\u6709\u70b9\u5927\u300d): the identity '
    + 'line alone was not the page. The design\u2019s Overview is six panels of dense rows \u2014 '
    + '`IV rank (1y) 71 60% \u00b7 60% n17` \u2014 and this side printed the band\u2019s word with two sentences '
    + 'under it, which reads as prose where the design reads as a sheet. **The one thing missing '
    + 'was the number the lens produced**, and it was in the payload all along: measured on DEV, '
    + 'every exhibit carries `verdict.value` with its own `unit`, and `track_record.by_side` carries '
    + 'both hit rates with their samples. '
    + 'A row is the design\u2019s four columns now: lens \u00b7 reading \u00b7 `5d% \u00b7 20d%` \u00b7 `nN`. '
    + '`lib/lensValue.ts` formats a reading by its own unit (a percentile as a whole number, vol '
    + 'points signed, a share of spot as a percentage) and refuses to guess a scale it does not '
    + 'know \u2014 a wrong scale is worse than an unfamiliar one. Each rate keeps its own denominator, '
    + 'the rule the long record line already followed. '
    + 'What moved rather than went: what a reading **means** is the panel headline\u2019s job and stays '
    + 'on every row as its title \u2014 one hover, where the long record sentence already lived. A lens '
    + 'that did **not** answer keeps its sentence on screen, because an absent reading has to say '
    + 'what is missing. Measured after: Volatility reads `IV Rank 20 \u00b7 58% \u00b7 67% \u00b7 n9`, '
    + '`IV-RV Spread 39 \u00b7 70% \u00b7 73% \u00b7 n15`, `OpEx pin 9.9% \u00b7 68% \u00b7 63% \u00b7 n24`. '
    + 'THIRD PASS, same evening, on the Owner\u2019s read again (\u300c\u8fd9\u4e2a\u548c Design \u7ed9\u7684\u5dee\u8ddd\u6709\u70b9\u5927\u5427\u300d): the '
    + 'rows were right and the **page** was not. What the two screenshots said side by side was '
    + 'structural \u2014 the design\u2019s Overview is two columns, six face cards and a rail, under a tab '
    + 'strip that divides the header from the body; this side had the tabs as one control among the '
    + 'header\u2019s buttons, no rail at all, and four page-level strips stacked between the title and '
    + 'the body so the cards began below the fold. '
    + 'THE FACES WERE CUT ON THE WRONG AXIS. They were the blueprint\u2019s six questions \u2014 Trend, '
    + 'Volatility, Positioning, Events, Forecast, Validation \u2014 and the design cuts them by the '
    + 'faces this page already has tabs for: Trend & structure \u00b7 Volatility \u00b7 Dealer levels \u00b7 '
    + 'Scenario \u00b7 Flow \u00b7 Events, each card a preview of the tab it opens. So Positioning split '
    + '(dealer gamma and order flow are two tabs and two questions \u2014 a card previewing two tabs '
    + 'cannot have an Open), Forecast took its tab\u2019s name, and **Validation left the grid for the '
    + 'rail**: it never had a lens of its own, it read every *other* lens\u2019s record, so as a card it '
    + 'repeated its neighbours. Ranked in the rail as `Record on <sym>` it answers the one question '
    + 'the cards cannot \u2014 of everything with an opinion on this name, which has been right. The '
    + 'blueprint\u2019s questions survive as each card\u2019s hover: the cut changed, the questions did not. '
    + 'THE CARD IS THE DESIGN\u2019S THREE PARTS NOW: a header that says where the face is read in full '
    + '(`Dealer tab \u2192`, and the link is this page\u2019s own tab), then a **verdict block** \u2014 colour '
    + 'bar, verdict, and one line of what it means \u2014 then the rows. The means line was missing '
    + 'entirely: the card said what it found without saying why that matters. '
    + 'EVERY NON-LENS ROW THE DESIGN DRAWS WAS ALREADY IN THE PAYLOAD, which is the measurement that '
    + 'made this pass cheap. `Walls 145 / 165` is `gex_regime.readings.major_put_wall` / '
    + '`major_call_wall`; the GEX flip is `zero_gamma`; `Close expectation` is '
    + '`terrain_regime.readings.expected_close`; `Structure \u00b7 VCP` is `sepa.readings.structure_score`; '
    + 'the OpEx count is `opex_pin.readings.dte` with its `expiry`. None of them costs a request. One '
    + 'does and gets it \u2014 `SEPA trend template 9 / 11`, because the exhibit carries the percentage '
    + 'and the repo already ruled that the count must be read from `tech_pass_count` rather than '
    + 'divided back out of a score. '
    + 'THE HEADER IS THE DESIGN\u2019S: `VERDICT` over the decisive lenses\u2019 own words, then '
    + '`n of m lenses decisive \u00b7 volatility drove the rating \u00b7 watchlist only`. **Drove the rating '
    + 'is the list\u2019s claim, not this page\u2019s** \u2014 a ranked table is an opinion about one thing, and '
    + 'only the table knows why it sorted, so both ratings pages now publish it on the trail along '
    + 'with the design\u2019s `WHY IT WAS THERE` chips (`composite 47.8 \u00b7 IV rank 33 \u00b7 VRP 57 \u00b7 '
    + 'terrain range`) and the weights they ranked under. The chips are the list\u2019s own numbers, '
    + 'formatted by the list, so the strip cannot disagree with the table you came from. '
    + 'CORRECTED FROM THE LAST PASS: **`/research/verdicts/{symbol}` is not 404.** The earlier note '
    + 'said there was no verdict store; the route exists, this app already reads it in the Copilot '
    + 'strip, and it answers with every claim the Copilot and the Loop have made on the name with '
    + 'its approval state. What is missing is narrower and sharper: the route is GET only '
    + '(`symbol_verdicts.py` declares one read) and no route in the research API accepts a stance. '
    + 'So `Your verdict` draws its lower half for real \u2014 the claims and their states \u2014 and says '
    + 'the form is not drawn because a Record button that kept nothing would be worse than the '
    + 'sentence. It offers a hypothesis instead, named as a different artifact rather than a '
    + 'stand-in. '
    + 'TWO MORE THINGS LEFT rather than were added: the **Copilot strip** leaves Overview (the rail '
    + 'now lists the very claims it summarised, with their states) and the **symbol picker** leaves '
    + 'every face but the two that need the as-of date beside it \u2014 the shell\u2019s own field sets the '
    + 'symbol and stays on the page, so a second box under the tabs was a second way to do one '
    + 'thing. Both stay where they are the only voice. '
    + 'Marked, not faked: the six read-artifact verbs (no artifact store, Owner deferred); the '
    + '`snapshot today / \u22121d / \u22125d` control (`/research/exhibit` takes no `as_of`, so a prior '
    + 'reading cannot be asked for \u2014 Since-last-snapshot compares against the last reading this '
    + 'browser saw instead); `Earnings` (no forward calendar reaches this side); `Forecast 30d hit` '
    + '(a record for a lens that returns no reading on any name, and its row already says so); '
    + '`Vol / OI top strike` (a per-strike reading that lives in the chain \u2014 Flow shows the two '
    + 'put/call ratios it does carry instead). '
    + 'The record rail\u2019s own honesty: it ranks by 20-day hit rate on the side each lens sits on, '
    + 'ambers a thin sample without moving it down the order (a 100% on n=9 genuinely tops the rate '
    + 'column; hiding it in the sort would hide the sample), and says how many of the records are '
    + 'this name\u2019s own \u2014 on MRVL two of five are, the rest answer `symbol_scoped: false` and are '
    + 'pooled across the universe. '
    + 'Swept: `1`\u2013`6` switching faces, `j` `k` stepping the list, the six `Open` links landing on '
    + 'their own tabs, the four capture verbs, the chips, the rail\u2019s claim list. No horizontal '
    + 'overflow at 1024 or 1600; the whole Overview fits one viewport at 1600. The chip tones took '
    + 'the P&L tokens at first and `check:legacy-css` caught it \u2014 \u00a714.7 \u2461: a bordered chip takes '
    + 'a lamp colour, and a hot lens is not a loss.',
  '/research/backtest':
    'Lab — Docs Index marks it LAB: "handed to lab (2026-09-12.3), the Trade original is deleted". Lab is not built here, so it stays until it is; absent from Trade is not retired',
  '/research/scan':
    'Walked 2026-09-21 against Research Scan.dc.html (Rev 2026-09-20.10) — the option side of '
    + 'Stock ratings, and deliberately the same page twice. What stood here printed the weights '
    + 'as a sentence (iv:25 vrp:25 slope:15 …) under a row of five lens chip filters: the model '
    + 'described rather than handed over. It now has the design’s left rail — Composite · '
    + 'Weights with the four preset tabs and five sliders, and the Tape panel — and the design’s '
    + 'own Why inspector on a row click, with j k esc. '
    + 'MEASURED FIRST, because the sliders only mean something if they can move the ranking: '
    + '/research/scan takes a **preset** and no per-weight parameter, so the composite is '
    + 'recomputed on this side from the same row fields the engine reads (iv_rank_1y and '
    + 'vrp_pct_252d are already percentiles; the slope and pin distance go through the engine’s '
    + 'own 50 + clamp(x × 200, ±50); terrain scores on pin_score). Recomputing all 500 DEV rows '
    + 'at the server’s neutral weights reproduced its composite_score exactly — max difference '
    + '0.0 — and again at the momentum preset over the 472 rows both windows share. So the page '
    + 'opens agreeing with the server and the Why panel can print both numbers; the points sum '
    + 'to the composite. Adapt is the server’s own fitted set, fetched rather than written down '
    + '(adaptive_30d is 30 days of lens hit rates, ~40ms for one row), and it is the reason a '
    + 'weight box prints 17.4 rather than 17 — rounding the fitted set would show a model that '
    + 'is not the one being applied. '
    + 'TWO NAME TRAPS, both measured: pin_score is **not** the pin lens — it comes from '
    + 'stock_forecast_terrain_daily beside regime and feeds the terrain component, while the pin '
    + 'lens is pin_pct_distance from the OpEx table; and terrain always counts, because the '
    + 'engine substitutes 50 for a null pin_score, so its weight stays in the divisor while a '
    + 'lens the row genuinely lacks (IV rank on 38 of 500) leaves both halves. '
    + 'EXTRACTED RATHER THAN COPIED (§14.2): the weights panel, the tape panel and the lens bar '
    + 'cell are one implementation in components/research/, read by both ratings pages. Two '
    + 'ranked lists one click apart that ranked or drew differently would teach the reader '
    + 'nothing they could carry between them. The Stocks page was re-pointed at the shared three '
    + 'in the same pass and re-checked beside its prototype. '
    + 'BETTER HERE THAN ON THE SIBLING, and worth saying because the sibling marks both as owed: '
    + 'the Rule column is real — strategy_opportunity rows carry a symbol list, so the cell '
    + 'names the active opportunity registered on a name and deep-links its chain at '
    + '/trade/rules?pick=opportunity:<id> (7 active covering 15 symbols, 14 of them in the '
    + 'scan’s 500). What it still cannot say is that the entry conditions are *met*: nothing '
    + 'evaluates those per name. And the capture ladder is drawn in full — pin · pool · '
    + 'hypothesis · plan — because all four already had somewhere to write. A pin from here is '
    + 'an iv hit stamped /research/scan, the same shape and origin the Pipeline census stamps, '
    + 'so the same name captured from a lane lands as one row rather than two. '
    + 'THE H1 STAYS “Vol ratings”: the prototype’s header still reads “Ratings · Underlyings”, '
    + 'but the design’s registry renamed this leaf when it flattened the two false Discover '
    + 'folds — four leaves, machine short names, ≤13 characters — and §5a.5 ties the h1 to the '
    + 'route label and the last crumb. '
    + 'Marked, not dropped: Earn (no forward earnings date reaches this side — '
    + '/research/events/calendar answers count 0 and the gap behind it is a vendor '
    + 'subscription; the design’s “veto a rule inside 10 days of a print” is the same absence '
    + 'twice); the per-lens 252-session band behind each bar (the row carries today’s reading '
    + 'and none of the lens’s history, so the bar is the score on its own scale); the Screen '
    + 'chip (nothing saves a screen yet, the same gap the Stock screen page names); and '
    + '“→ Autopilot objective”, which writes a standing schedule and whose source stamp is the '
    + 'same open product question the Stocks page carries. '
    + 'Kept though the design does not draw them: Ask Copilot, whose snapshot is this page’s own '
    + 'numbers, and the symbol trail the Symbol page reads to say “From Underlyings · 3/19”. '
    + 'Elsewhere rather than gone: the five per-row Labs links moved into the Why panel — the '
    + 'prototype’s own footer says so — and CompositeRegimeRibbon, a per-symbol reading, stays '
    + 'on Symbol where it belongs. '
    + 'Swept: 19 rows on DEV at Both, both segment controls into the URL, four preset tabs, a '
    + 'slider to Custom (Σ 130, and the divisor is the applied weight so the ranking stays '
    + 'valid), the row click into ?sym=, j k walking one step each way, esc clearing it, the '
    + 'Rule link, the symbol link, and the four verbs. No horizontal page overflow at 1024 or '
    + '1440; the inspector docks at 1600 and floats at 1024, per the one dock formula. '
    + 'At the server’s own weights nothing in the book clears 70, so Hot is empty and the tape '
    + 'reads Mixed — reachable by moving the weights, which is the page’s point.',
  '/research/ratings/stocks':
    'Built from nothing 2026-09-21 against Research Ratings Stocks.dc.html, then re-walked the '
    + 'same day after the Owner read it beside the prototype: the colour was off and the ranked '
    + 'list was too long. Both were real, and the second was the worse of the two. Measured '
    + 'before building: /research/sepa/model/daily returns 500 rows carrying four component '
    + 'scores per symbol — trend_template_score, fundamental_score, momentum_score, '
    + 'structure_score — and, in factors_json, **the weights the server combined them with** '
    + '(trend .35, fundamental .30, momentum .20, structure .15). sepa_score is that combination '
    + 'and it reconciles, so the sliders recompute the same number rather than decorating it, '
    + 'and the page opens agreeing with the server. The Why panel takes it apart: points are '
    + 'score × weight over the weight actually applied, and they sum to the composite. '
    + 'THE LENGTH: the first build drew all 500 in one list. The design has a filter bar and the '
    + 'app had skipped it. Universe reuses usePortfolioSymbols (the same holdings/watchlist '
    + 'membership the PortfolioTag reads, so the chip and the filter cannot disagree) and '
    + 'defaults to Both — nine names on DEV rather than five hundred. Show is the design’s '
    + 'hot/cold at 70 and 35, and it is worth knowing that cold is reachable only by moving the '
    + 'weights: at the server’s own the composite floors at 47.9 and 0 of 500 are cold, while '
    + 'Quality-led puts 62 there. Both counts are read off the universe you chose, so they are '
    + 'the denominators of the list underneath. The list stops at 200 rows and the title says '
    + '“200 of N” when it does. THE COLOUR: the lens cells drew a solid bar filled to the value '
    + 'in green or red, which put four columns of saturated colour across every row and left the '
    + 'tags and grades competing with it; the design draws a quiet track with a thin accent '
    + 'marker and colours only the number, and so does this now. Grade · path is coloured by '
    + '**path** rather than grade, which is the design’s own choice and a different reading — '
    + 'grade splits 15 A / 298 B / 187 C and colouring by it made every A green while saying '
    + 'nothing about whether the name is actionable. The Tape panel went from two columns of '
    + 'tall blocks to the design’s thin row, and gained the verdict sentence it was missing. One '
    + 'colour difference is **not** a gap: the prototype renders its ticker in lime because '
    + '.os-sym hard-codes #a3e635, which its own skin contradicts — shell-registry puts '
    + '/research/* in the analysis layer, whose accent is #60a5fa, and that is what both the '
    + 'app and the prototype’s own tokens resolve to. The app follows the layer. '
    + 'FORM: Trend and Growth now read as counts of checks passed, 11 and 8, because that is '
    + 'what the two scores are — trend_template_score takes only the eleven values n/11 × 100 '
    + 'and 231 of the 500 rows sit at exactly 100, so a column of percentages was a column of '
    + 'hundreds while 10/11 beside 11/11 still says something. The count is read from '
    + 'tech_pass_count / fund_pass_count, never derived from the score: a score without its '
    + 'count stays a score. '
    + 'Marked, not dropped: a relative-strength lens (no RS field on this row, so the Tape has '
    + 'four bars where the design has five); Earn (no future earnings date reaches this side — '
    + '/research/events/calendar, /research/events and /research/event-radar/events all answer '
    + 'with count 0, and the vendor gap behind them is a subscription one); Rule (the store '
    + 'answers and holds nothing today, but the shape is the harder half — a playbook rule '
    + 'carries a title, a category and prose, with no symbol and no predicate, so nothing can '
    + 'decide which rule a row matches); the per-lens 1-year band (high_52w/low_52w are price, '
    + 'not lens history); the saved-screen filter (nothing saves a screen yet, the same gap the '
    + 'Stock screen page names); and the Why panel’s settled record (the outcome store settles '
    + 'candidates the loop nominated, not rows of this list, so there is no prior set to count). '
    + 'Owed, not marked: the row’s Pin / Pool / Hypothesis verbs and the two header buttons. '
    + 'Each writes somewhere — the shelf, the Candidate Pool, the Book, the loop’s schedule — '
    + 'and what this page stamps as the source of a write is a product call, which is the same '
    + 'reason the six-verb row was deferred on 2026-09-21. Plan is built, because it navigates '
    + 'rather than writes and /trade/plans reads both ?symbol= and ?new=1. '
    + 'Interactions swept on local DEV (:5173): 18 links, every symbol to Symbol and every Plan '
    + 'to the Plans desk, both destinations reading their params; rows carry role=button, a '
    + 'keyboard route in and a pointer, and open the Why panel with the name in ?sym= so an '
    + 'argument about one can be sent to someone; Escape closes it and clears the param; links '
    + 'inside a row stopPropagation; no horizontal overflow at 1024 — the table scrolls inside '
    + 'its own wrapper. An empty list names the filter that emptied it rather than showing '
    + 'nothing. One thing this page surfaced and the component fixed: SectionPanel painted its '
    + 'body bg-card, the canvas colour, so every panel was the same shade as the page behind it '
    + 'and the whole page read flat. The design’s panel is a well — body on --sk-ground '
    + '(bg-background), header on --sk-surface (bg-secondary), which exist here value for value '
    + '— and the Owner chose to change the component rather than override it here, so Portfolio, '
    + 'Risk, The Book and Review › Objectives gained the same depth in the same commit. '
    + 'Owner signed off 2026-09-21 on local DEV (:5173) at this rev.',
  '/research/screener':
    "Owner ruled 2026-09-20 which of this side's pages the design's Stock screen is, and the "
    + "page took the design's own path with the name. The evidence is the prototype's content, "
    + 'not the label: Research Screener.dc.html is universe -> criteria stages (AND between '
    + "stages, OR inside one, 'at least N of these') -> results -> lineage v1->v2, and only "
    + 'this page has any of the three. Stock Explorer has no criteria of its own; it is a tab '
    + 'shell over SEPA Daily Core, Momentum Radar and Event Radar, all three of which the '
    + 'design redistributed. An earlier note in routeRegistry read the design’s Screener as our '
    + 'Explorer; that reading is withdrawn. The old `/research/stock-screener` address redirects '
    + 'here; `/research/screener` stopped being a redirect to the Option Screener, which means '
    + 'an option-screener bookmark written before 2026-09-15 now lands on a stock screen. '
    + 'First walk against the prototype 2026-09-20, cell by cell, under the interaction '
    + 'standard. Measured before building, on DEV: `criteria-stats` carries a per-condition '
    + 'pass count for the eleven technical and eight fundamental conditions over a universe of '
    + '5319 at eval_date 2026-09-19, plus a pass_count_distribution for each — and that '
    + 'distribution IS the design’s `min` stepper, because “at least N of these” is its tail. '
    + 'So the first two stages are live, chips and stage totals both. The other five are not, '
    + 'and each is marked with its own reason rather than dropped: Momentum and Structure read '
    + '200 with a count of 0 and a note naming dw_stock.mart_sepa_tier_* as awaiting 252+ '
    + 'trading days; Quality returns nothing for all seven of its ids while the same endpoint '
    + 'returns rows for the growth conditions, which is what makes it “no data for these '
    + 'conditions” rather than “the endpoint is down” — that distinction cost a cross-check and '
    + 'is the only reason the row can say which; Catalyst and Options have no screen ids on '
    + 'this side at all. Built: the design’s three columns — the universe rail, the Criteria '
    + 'funnel, and results — with the funnel as the page’s criteria surface. It drives the '
    + 'page’s own filter sets rather than keeping a second copy, so a chip toggled in the '
    + 'funnel is the same selection the apply flow reads. Divergences. Each stage’s number is '
    + 'measured against the universe, not against the stage above it: the prototype runs an '
    + 'intersection down the column, and reading the symbol lists for every bucket in both '
    + 'tails would be up to nineteen requests per click for a number the applied screen already '
    + 'answers. The fall is still visible because both stages are counted against the same '
    + '5319, the header says “universe · narrowest stage” rather than implying one ran into the '
    + 'other, and the footnote states which reading it is. The rail’s Presets and My screens '
    + 'are empty with their reason: nothing saves a screen here, and the design’s two writes '
    + '(Workbench preset, Autopilot objective) both go through a Decision Inbox card that does '
    + 'not exist on this side. Not built, and reported rather than faked: the artifact id and '
    + 'the v1->v2 lineage strip (no artifact store — the same gap The Book’s Journal band '
    + 'names), the Explain provenance panel, Rank by (its target, Stock ratings, is unbuilt), '
    + 'the Capture verbs per row, the “Rule that would take it” column, and the Why-it-passed '
    + 'panel. The page’s earlier arrangement of the same conditions — two hero cards and two '
    + 'collapsible filter panels — is still below the funnel under a line saying so: the design '
    + 'replaces both, but what each carries that the funnel does not (the distribution '
    + 'histogram, the tier cards) is a deletion for the Owner to rule on, not one to make in a '
    + 'walk. Interaction sweep: the min stepper moves the count and was clicked (8 -> 9 took '
    + '1,610 to 1,270, which is the distribution’s own tail); a chip toggles, lights, and '
    + 'raises the page’s filter count; Clear empties it back to “nothing selected”; the five '
    + 'inert stages are disabled and say why on hover rather than looking live. No page-level '
    + 'link is drawn to a destination that does not exist — the prototype’s Method and Journal '
    + 'links have no page here and are left out rather than pointed at something approximate. '
    + 'Owner review 2026-09-20 rejected that first pass on two counts, both correct. **The '
    + 'presets were not missing.** The note had said “no preset store on this side”; three '
    + 'of the design’s four name readings this app already produces, two from pages that '
    + 'work today. The probe that produced the wrong answer hit `/research/sepa/daily`, the '
    + 'screener-wide rank table, which carries no `path` at all — the route the page itself '
    + 'calls is `/research/sepa/model/daily`, and it answers 298 SETUP + 15 PIVOT. The rail '
    + 'now loads them: SEPA Daily Core (313 names) and Momentum Radar (A+ and A) land in '
    + 'Results on a click; Event Radar and Premium seller stay greyed with their reasons. '
    + '**And the Momentum stage was mis-marked.** It had been called dead on '
    + '`momentum-filter`, whose tier mart is still accumulating — but '
    + '`/research/momentum/radar` answers today, so the stage is live and its chips carry '
    + 'real counts. The lesson is in the skill now: a stage is dead only when every source '
    + 'for it is, so a reason has to name the endpoint rather than say “no data”. Those '
    + 'counts are **unique names, not rows** — the radar returns a row per symbol per date, '
    + 'so grade A is 92 rows over 56 names, and every other chip on the panel counts names '
    + 'out of the universe; two chips side by side meaning different things is worse than '
    + 'either being wrong. Grades B and C come back at the route’s 500-row cap and print '
    + 'with a `+`. The review also found the page functionally broken: the funnel selected '
    + 'conditions at the top and the only control that did anything with them was the old '
    + 'Search/Apply bar at the foot of the page, below the fold. `Run → Results` now sits in '
    + 'the funnel’s header beside Clear, runs the preview and applies it in one press '
    + '(`runFilter`, awaited — syncing the two through an effect is where a cascading render '
    + 'starts), and the panel reports how many names landed. Verified by clicking: a preset '
    + 'fills Results with its names, a chip lights and Run fills Results from it. '
    + '**Signed off 2026-09-20 knowing it is not finished.** The Owner’s call: the funnel, '
    + 'the rail and the loop are enough to use, and the rest waits for another round rather '
    + 'than holding the queue. What is still open, so the state does not read as done: the '
    + 'artifact id and the v1->v2 lineage strip; the Explain provenance panel; Rank by, '
    + 'which is blocked on Stock ratings being unbuilt; the Capture verbs per row; the '
    + '“Rule that would take it” column; the Why-it-passed panel; and the four stages that '
    + 'stay marked (Structure, Quality, Catalyst, Options). The page’s earlier arrangement '
    + 'of the same conditions — two hero cards and two collapsible filter panels — stays '
    + 'below the funnel by the Owner’s decision, not by omission.',
}
