/**
 * Design-walk notes · Research › Pipeline (Discover and Analyze).
 *
 * The stations a reading passes through before it becomes a candidate: the two
 * ratings pages, the two screens, and the Symbol page they all open into.
 *
 * Split out of `research.ts` on 2026-09-21, when the Vol ratings walk pushed
 * that file past the 800-line ratchet. The seam is the one the menu already
 * draws — Pipeline's own rows on one side, the loop and the Copilot that
 * consume them on the other — so a reader looking for a note knows which file
 * without opening both.
 */
export const RESEARCH_PIPELINE_NOTES: Record<string, string> = {
  '/research/compare':
    'Built 2026-09-23 against Research Compare.dc.html at Rev 2026-09-23.24, on the design\u2019s option (b) for the three inputs this data plan does not carry and on the Owner\u2019s answer to where the rows come from. WHERE THE ROWS COME FROM (Owner 2026-09-23): the prototype\u2019s view reads \u201cfrom Symbol verdict\u201d, and verdicts here are prose claims with no stance, level or horizon, so the view is typed on the page (stance \u00b7 floor \u00b7 ceiling \u00b7 days, on the address) and says so beside it. The structures are the active rules in Trade \u203a Rules whose dimensions match the stance \u2014 sell vol reads short_vol, bullish and bearish read direction, buy vol reads long_vol \u2014 so on DEV a sell-vol view gives five of the six (bear call, bull put, CSP, covered call 10% OTM, iron condor). The prototype\u2019s calendar and 1\u00d72 ratio are not rules here and do not appear; a rule with no placement is a row that says why. Until the reader types levels, floor and ceiling are \u00b110% of spot and an amber note says they are nobody\u2019s view. PLACEMENT, stated under the table: a short put at the highest listed strike at or below the floor, a short call at the lowest at or above the ceiling, a spread\u2019s wing about 5% beyond its short (the rule\u2019s legs carry no wing rule), a covered call by its own otm_pct, a bull call spread long at the money. Expiry is the first listed at least the horizon out, a monthly when the rule\u2019s time dimension says monthly. MEASURED (DEV 2026-09-23, PLTR): the plugin\u2019s end-of-day chain for 16 OCT answers 122 contracts with one untraded; spot is the session\u2019s close from the same day as the chain; the research route /research/option-expirations answers 404, so expiries are read from the plugin\u2019s own catalogue (new fetchChainExpirations). BUILT, per Rev .24\u2019s table: legs in the design\u2019s own line (STO 172.5P \u00b7 16 OCT @ 2.36), net, backing, \u0394 \u00b7 vega \u00b7 \u03b8, the payoff overlay, \u2192 Plan (to Plans narrowed to the name, the same door Option screen\u2019s \uff0b Plan is \u2014 Plans takes no contract), and How big with the backing cap as room to the 85% gate \u00f7 one unit\u2019s backing, read from the same exposure hook Risk \u203a Sizing cites. HALF-BUILT: the conviction cap is Playbook stats\u2019 own size-cap rule (full \u00b7 half under the sample floor \u00b7 none under profit factor 1.2) applied to the strategy service\u2019s record by structure and taken as a share of the backing cap; the label is written out in full (Cash Secured Put \u00b7 by structure: 19 closed, 95%) with regime split owed in grey, and never the prototype\u2019s \u201cIV rank > 65\u201d. OWED, IN PLACE: the tail cap bar reads \u201ctail cap \u00b7 needs the 20-day distribution \u2014 not computed\u201d and every size carries \u201c2 of 3 caps\u201d \u2014 on DEV that is the whole point, because without the tail cap the backing room sizes a bull put spread at two hundred units, and a missing cap only ever makes a size too large; POP \u00b7 EV 20d \u00b7 p10 are \u2014 with the reason on the header; Can you get filled is the EmptyState in the design\u2019s exact words plus its optional liquidity line per structure (the thinnest leg\u2019s OI and volume, \u201ca liquidity proxy, not a spread\u201d); \u2212 fills and EV net are \u2014, and the page\u2019s header line reads \u201cEV net of fills \u00b7 owed (quotes)\u201d. The payoff band (20-day p10\u2013p90) is not drawn and the caption says so. EXTRACTED BEFORE DUPLICATING (\u00a714.2): the size-cap rule moved from Playbook stats to utils/sizeCap.ts with a record-shaped input, since Compare is its second reader (the prototype\u2019s own words: \u201cfeeds the conviction cap on Compare\u201d); parseOptionTicker joined buildOptionTicker as its inverse; positionGreek, daysTo and winRateBand are reused as they were. DIVERGED, EACH WITH ITS REASON. The Margin column is Backing: the gate this page divides is Backing & Model\u2019s pool, which charges a short put its strike and a spread its width, not the broker\u2019s Reg T margin, and dividing a backing room by a margin figure would mix units. Premiums are the session\u2019s last trade (day_close), not a mid, because the plan carries no quote, and every place a premium appears says so. Swatch colours are the identity tokens (contract \u00b7 strategy \u00b7 instance) and amber, not the prototype\u2019s literals. The \u201ctrade-off, in words\u201d panel writes each structure\u2019s sentence from its numbers rather than the prototype\u2019s hand-written prose, and a structure sized to none says which cap refused it. DOORS OPENED: Option screen\u2019s \u21c4 Compare, drawn disabled until today, now opens this page with that contract\u2019s strike as the floor (checked by its href; DEV\u2019s screener has no contract row to click); Risk \u203a Sizing\u2019s sentence no longer says Compare is unbuilt, and says instead that Compare hands on a Plan rather than a sized candidate; Signal Decay\u2019s comment says Compare reads conviction off the structure\u2019s record, not a lens\u2019s decay \u2014 its visible sentence was already true. Swept: the ticker, four \u2192 Plan links and Playbook stats; a row click toggles its curve (aria-pressed); the stepper steps from the previous value (five clicks, five steps \u2014 a first version stepped once); over-cap turns the size red and the binding cell amber; bearish leaves only the bear call spread; a typed floor rewrites the address and re-places the puts. Checked at desktop and 1024: no page overflow, the fifteen-column table scrolls in its own container.',
  '/research/history':
    'Built 2026-09-23 against Research History.dc.html at Rev 2026-09-17.1, on local DEV (:5173), in the prototype’s order: IV vs realized across the page, then the vol cone, earnings moves and correlation over time. Measured before it was built, and the measurement is most of the page. HOW MUCH PAST THERE IS: the vrp store answers 251 sessions of RV20 whatever is asked for (a year, not the design’s 2y); IV30 is continuous for about three months — PLTR has 72 readings, 71 of them from April, AMD has 11 because the store holds only 11 AMD sessions at all; the RV cone reads 488 sessions of daily closes at five horizons; the ATM term answers 19 expiries for PLTR. So every figure carries the count it was taken over, a window the store cannot fill says so in amber (the store holds 251 of the 504 sessions this window asks for; IV30 covers 72 of those sessions, from 2025-11-05), and the percentile is withheld under 20 readings. THE FINDING, AND WHY THE PERCENTILE IS WITHHELD ON DEV: the store’s IV30 is full of faults through June and July. PLTR reads 0.074, then 2.256, then 0.544 on consecutive sessions, and 2.642 sits between 0.566 and 0.040; NVDA, RKLB and HIMS carry the same shape; from August it settles. A percentile over those readings ranks the faults. The page names each suspect reading — below 5 vol, or 1.8× away from both IV-bearing neighbours in the same direction; an edge reading is judged on the floor only — and withholds the percentile, the band and the IV-over-RV share while any sit in the window. It does not drop or repair them: that would be this page defining clean IV30 a second time, and the store owns it. PLTR shows nine in its 6m window. BUILT: the header (the ticker opens its Symbol page; the ⧉ face switch with Method drawn disabled because /research/lab/history is not built, and the design’s second way there, Method → window · estimator, as plain text with that reason in its title); the window control on ?win= (6m by default, the prototype’s own state); IV vs realized with IV30 · RV20 · VRP read from the store’s newest row, nothing recomputed; the percentile as the share of the window at or below today, which is the design’s definition and not iv_rank; the 20th–80th band; and the vol cone — the store’s p05–p95 and p20–p80 bands, the median dashed, and today’s ATM IV at each horizon interpolated in total variance between the two listed expiries around it, left off where there is no pair rather than extrapolated. OWED, EACH PANEL KEEPING ITS PLACE AND SAYING WHAT IT WAITS ON: Earnings moves needs print dates, which no store here holds. Two of the row’s three figures are measurable today — option daily bars reach back two years (checked for PLTR around 2024-11, 2025-08 and 2025-11 prints), and the actual move comes from daily closes — and the dates come from the market-data plugin’s 0.37.0 (8-K text, Item 2.02 is the results release; six sampled names carry eight or nine quarters each), written and pushed, not yet released. Correlation over time needs a series: /analytics/risk/correlation answers today’s matrix only, which Risk · Portfolio Exposure already prints; computing a rolling ρ here would give the book a second correlation that could disagree with Risk’s. The panel links Risk →. The prototype’s earnings dashes on the IV chart wait on the same dates and the legend says so. EXTRACTED BEFORE DUPLICATING (§14.2): the IV-vs-RV chart is Symbol’s VrpTimeSeriesChart with three opt-in props (which realised series, an IV band, fluid width), Symbol’s own call unchanged; the RV cone got the fetcher its schema had been waiting for (RvConeSchema had no reader); the ATM term is the fetcher Option Discovery already uses; ordinal is analyzeDepth’s own, now exported; the band’s quantile is utils’ interpolated one. DIVERGED, EACH WITH ITS REASON. The band uses the shared interpolated quantile rather than the prototype’s floor index — a fraction of a vol point, and one definition of a percentile in the app is worth more. The header caption features.option_metric_* · 2y is not drawn: the page reaches three stores at three depths, and each panel states its own. The cone’s sentence counts horizons (above the median at n of m, above the 80th at k) instead of the prototype’s characterisation of one cone as a front-month premium. VRP is coloured by sign, as the prototype does. Also measured and not used: /analytics/options/iv-percentile names its fields _1y and reports lookback_days 75 for PLTR (11 for AMD), and its iv_current reads 56.4 where the vrp store’s IV30 reads 46.4 the same day — this page reads the vrp store only, and the other number is worth a look where it is quoted. Checked at desktop and at 1024 (no overflow; the three lower panels stack). Swept: two links (the ticker, Risk →) and three disabled marks, all clicked; the window control rewrites ?win= and the reading follows; the History row stands under Analyze and lights on this route.',
  '/research/signal-decay':
    'Walked 2026-09-22 against Research Signal Decay.dc.html at Rev 2026-09-17.1, rendered side by side with the app on local DEV (:5173). The page was a per-lens instrument — pick a lens, a window and a regime and read that one signal’s hot/cold matrix, its intersections and its symbols — and the design’s page asks a question no amount of picking one at a time answers: which of them is slipping. So the design’s roster leads and the instrument stays below it under One lens, up close. Built: the Signals roster (12 rows, worst drift first), the amber Decay alerts panel above it, the design’s header line and its Playbook stats →, and the footer that carries the page’s whole argument. The rule, in the design’s own words: decay is judged against each signal’s own 1-year average, not against other signals — a 55% signal drifting to 40% is decaying, a 45% signal holding 45% is not. The endpoint takes a window_days, so now and its own year are the same call asked twice, 90 against 252. Measured on DEV 2026-09-22 for vrp hot: 40.1% on 152 settled at 90 days against 43.7% on 245 at 252, which is a −3.6-point drift. The page proves its own rule on the live data: Gamma · cold reads 38% and is not decaying, because 38% is eight points above its own year. The unit is a lens side, not a named strategy. The design’s signals are written prose (IV rank ≥ 60 short vol, 25Δ RR reversal); this side’s registry has six decay lenses and each fires hot or cold, which is the thing the engine measures a hit rate for — so a row is IV Rank · hot, named as the engine names it rather than dressed up to look like the design’s. Twelve rows, from six lenses asked twice. Thin samples are the design’s rule and this side already had the number: THIN_SAMPLE = 10 in symbolRecord.ts is exactly the design’s grey month is n < 10, not a bad month, so the sparkline greys a week under it and a drift is never called a decay on fewer than ten settled outcomes. Five of the twelve rows currently read nothing has settled at 20 days yet — the window has not closed — which is a fact about the horizon, not a zero. Owed, named in the footer rather than drawn empty: Profit factor. The response carries hit rates and no payoff, so there is no field to read and a PF column would be a claim the engine cannot make; the design’s second alert condition (PF < 1.2) goes with it, so an alert here fires on drift alone and the footer says so. Diverged, each with its reason. The 6-month trend bars are the engine’s weekly 5-day rolling rate — the only series it keeps — so the column is labelled for what it is rather than letting a 20-day header sit over a 5-day chart; the design’s months become 26 weeks, which is the same six months in the unit the data has. The design’s alert line says it zeroes the conviction cap in Compare; Compare has no page on this side, so the panel names where the credit would flow instead of linking into nothing. Extracted before duplicating (§14.2): pct(0–1 rate → whole percent) existed three times — in this page, in bookExplanations and in the roster this walk added — and fmtPctFromFraction(v, 0) in lib/format.ts was already exactly it. All three now call the shared one; the ratchet caught the fourth copy the moment it was written. Owner signed off 2026-09-23 on local DEV (:5173) at this rev.',
  '/research/contract-screener':
    'Walked 2026-09-22 against Research Contract Screener.dc.html at Rev 2026-09-19.2, rendered side by side with the app on local DEV (:5173). The design’s own description places this page third — Stock Explorer picks companies, Option Scan picks underlyings with premium, this picks the contracts that fit a structure — and the page had no first step at all: it opened on an empty textarea, asking the reader to retype a list three other pages already hold. It also had no funnel, which is the design’s one device for the thing this page does most, which is return nothing. Built: the four-cell funnel strip; 1 · Underlyings with the design’s source buttons and droppable symbol chips; the numbered rail around 2 · Structure and 3 · Filters; the design’s header line; and an empty state that points at the funnel instead of shrugging. The finding of this walk is that the engine is dark, and it is measured rather than inferred. POST /research/screener answers ok:true with total_contracts:0 for every symbol tried — including ANET, which the market-data plugin’s own coverage reports as 2,150 option contracts across 21 expiries, newest stamped the same morning. It answers the same at every source value (massive, ib, polygon, chain, snapshot and omitted) and with the filters opened to their widest: DTE 7–120, P(ITM) ≤ 90%, return ≥ 0, spread ≤ 50%, premium ≥ 0, earnings allowed. The engine gives the same reason each time — No snapshot data, run Market Data Plugin sync first — so the emptiness is neither the filters nor the symbols: the screener reads an option snapshot store that the plugin’s contract coverage does not fill. The contracts table is therefore deliberately not rebuilt. It cannot be checked against a single row, and reshaping a table against a design without ever seeing it hold data is the walk failing quietly. What is built is the half that makes a dark engine legible: the funnel names the stage that emptied and carries the engine’s own sentence for it, which is exactly the job the design gives it. Three of the design’s four sources exist and are measured: Option Scan · IV-rich today reads the scan’s own lens_flags.iv_rank, and hot is its word — 121 of the 500 it ranks; Watchlist holds 22; In the book is the 11 watchlist rows the importer filed from positions, which is where this app records that a name is held. The fourth, Stock Explorer · a saved screen, has no store — nothing on this side saves a screen — and is drawn disabled with that reason rather than left out, because a picker with three options where the design has four reads as a smaller idea rather than a missing one. A source is capped at three names, and the cap is measured, not chosen: two names answer in 15s, three in 31s, and five and eleven both exceed the client’s own 60-second abort and show a timeout instead of a result — roughly ten seconds a name. A button that fills the box with 121 names and then always times out is worse than one that takes three and says so, which the panel does, once, under the list. Diverged, with its reason: the Run button stays, against the design’s live — no Run button. At ten seconds a name a live re-run would fire a half-minute request per slider drag; the design’s phrase describes a prototype that computes its chain in the browser. Structure: the design enables cash-secured put and covered call and refuses the two spreads; this side enables only the put, and the three refused are drawn and disabled with the reason — the spread structures need two legs priced together, which the engine does not do — because a structure missing from the picker reads as a structure nobody trades. Not built, and owed rather than missing: the contracts table’s own columns (Rule, Cash/ct, the ⇄ Compare and ◫ Discovery and ＋ Plan row actions) and Save as rule → from the filters. Each needs rows to be built against, and the page has none to show; the per-symbol Save-as-Opportunity this side already had is untouched and still reaches the same store. REBUILT 2026-09-23 against Research Contract Screener.dc.html at page rev 2026-09-20.10, on the Owner’s option A: build the design’s page now and fix the engine separately. The walk of 2026-09-22 had kept a Run button and left the table unbuilt because the engine answers nothing on DEV; the Owner read the page as far from the design, and it was. Now in the prototype’s order: the header with Export CSV and Save as rule →, the four-cell funnel, and the numbered rail beside a Contracts panel that is always drawn. LIVE, NO RUN BUTTON: the engine is asked once per name, structure and earnings choice at the widest window a slider can reach (DTE 7–120, no P(ITM), return, spread or premium floor), and the six sliders — the design’s ranges, steps and read-outs, in its units, not the old 0–1 fractions — filter that in the browser, so a drag never refetches. One request per name, because three in one request ran past the 60-second abort at that window (measured); asked separately each name stays inside it, names fill in as they answer, and one that times out costs only itself. Earnings is the one filter left on the server: the response carries no earnings date, so toggling it re-screens, and the toggle says so. The table is the design’s eleven columns in its order, grouped by underlying, best annualised return first, the top four a name, with the design’s formula (premium ÷ cash secured × 365 ÷ DTE, the mid as premium, strike × 100 as the cash) and its three colour rules (Δ lime inside −.15 to −.35, return green from 20%, spread red past the slider). Rule is the Decision Inbox’s own join (ruleThatFits over the Opportunities book) rather than a second one. A row click selects it; the ticker on a group row opens that name. MEASURED, AND WHAT DEV CANNOT SHOW: no contract row at all. Every name comes back with no chain — the engine’s own sentence, “No snapshot data — run Market Data Plugin sync first”, is a guess: its two plugin helpers swallow every outcome into an empty list, and the real cause is the market-data plugin’s /options/chain/latest answering 0 rows (in 18–30 s) for keys that exist, while its expirations endpoint answers in 0.1 s. That is tracked as its own task. So the row, the colours and the three actions are checked by the model’s tests and not against a live row; a re-walk with data is owed the day the plugin answers. What the page does show on DEV is every name as a group row carrying the engine’s sentence, the funnel naming the stage that emptied, and Passing only saying ‘No name has a chain … no slider will change it’ rather than the design’s ‘every contract fails a filter’, which would send the reader to the sliders for a fault in the chain store. DIVERGED, EACH WITH ITS REASON. The engine’s score, rating and risk are not columns, since the design draws none; they stay on each row’s hover and in the export. The group row prints spot and average IV, the two the response has; the design’s IV rank and days to earnings are not in it, and the quote time in the panel header is not either, so neither is drawn. The Option Scan source dot is amber, not the prototype’s red: red is kept for a real fault (§1) and ‘IV-rich today’ is a reading. Compare ⇄ is drawn disabled with its reason — /research/compare has no page. Discovery ◫ opens the Symbol page’s Chain tab, which is where /research/discovery went. ＋ Plan opens a new plan on Plans narrowed to the name; the contract and the rule are not carried, because Plans takes no contract. Save as rule → prefills the name, the symbols and an explicit-symbols scope; the six filters are not written as entry conditions, which the reader sets. Covered call is drawn and refused where the design enables it — the engine screens only the cash-secured put. The page title stays Option screen, its menu label (§5a.5), where the prototype heads it Contract Screener. Ask Copilot stays beside the design’s two actions, as on every Research page, and the three wrap below the long lede in the shared PageHeader rather than sitting beside the title. Saved state moved to a new storage key, because the sliders changed units and an old 0.3 would have read as 0.3%. Checked at 1680 and at 1024 (no horizontal overflow; the rail and the table stay side by side). DOOR OPENED 2026-09-23: ⇄ Compare now opens /research/compare with the row\u2019s strike as the view\u2019s floor, the day that page was built; the disabled state and its reason are gone.',
  '/research/backtest':
    'Walked 2026-09-25 against Research Backtest.dc.html at route rev 2026-09-22.6, on local DEV '
    + '(:5173) \u2014 the pending pool\u2019s last page. Measured first: research.backtest_run holds 43 runs '
    + '(long_stock_event 37 / long_atm_straddle 6; earnings 42 / opex 1; 30 with a thesis), every one '
    + 'with a full summary and none with walk-forward or benchmark payloads; the settlement endpoint '
    + 'answers cross-symbol, newest 200, with direction/path/close-zone in stats_json and no claimed '
    + 'probability. Rebuilt run-first per the design: the persisted runs list is the spine (id, '
    + 'template \u00b7 event \u00b7 scope, n coloured at the 5/30 thresholds, win, Sharpe withheld under 5, '
    + 'thesis), a click opens the detail, the builder moved behind \u2795 New run, and Rerun seeds the '
    + 'builder with the run\u2019s symbols and thesis. The run card gained the confidence tag, win/loss '
    + 'bar, and equity + per-event histogram drawn from real event trades only \u2014 a persisted run '
    + 'carries none and says so in the design\u2019s own words. Fixed in passing: the card\u2019s walk-forward '
    + 'and benchmark types described payloads the server never sent (window_index/in_sample_return vs '
    + 'the engine\u2019s is_start/oos.sharpe_annual; annualized_return vs cagr) \u2014 unnoticed because 0 of '
    + '43 runs carry either; both now read the engine\u2019s own shapes through tolerant parsers with '
    + 'tests. Diverged, named: the equity chart has no dashed benchmark line (the server stores SPY '
    + 'metrics, not a series \u2014 they render as tiles); the walk-forward label says IS 12m \u00b7 OOS 3m, '
    + 'the server\u2019s real parameters, not the design\u2019s 6m/2m; no IS column and no OOS/IS decay \u2014 the '
    + 'engine sends fit=null, unmeasured not omitted; Settlement keeps the store\u2019s own vocabulary '
    + '(direction/path/close-zone badges) where the design invented regime and claimed-p columns, and '
    + 'the calibration tile keeps its place saying no claimed p is recorded; the grain segment is not '
    + 'drawn (sessions carry no 2d/5d in the store); the date-range filter, an existing capability the '
    + 'design does not draw, stays. Hypothesis \u2192 lands on the board (no per-id focus there yet). '
    + 'Owner to look before aligned.',
  '/research/lab/screener':
    'Built 2026-09-24 against Research Stock Screen Method.dc.html at route rev 2026-09-20.4, on '
    + 'local DEV (:5173). Measured first: /analytics/sepa/screener-wide serves the whole mart \u2014 '
    + '3,446 rows @ eval 2026-09-24, every one of the 19 condition booleans by name, crs_percentile, '
    + 'return_252d and company_name, no nulls in the sampled fields \u2014 and the dbt case rules for '
    + 'grade/stage/path (mart_sepa_feature_daily) re-applied over it were verified 1000/1000 against '
    + 'the model store, whose own endpoint caps at its top 1000 and so cannot serve this face. '
    + 'Built: the filter vocabulary aside (symbol/company search, path and grade chips, min-composite '
    + 'slider, all 11 trend and 8 fundamental conditions as required-checkboxes, each carrying its '
    + 'real pass share of the evaluated universe), the sortable authoring table with per-row condition '
    + 'dots, the honest empty state naming the active filters, and the read-only-in-Trade tag. '
    + 'Diverged, named: the fixture filled its pass dots in failure order because it held only counts '
    + '\u2014 the store serves every boolean, so all 19 dots are real and that disclaimer retired with '
    + 'the fixture; the fixture drew 24 rows, the real universe is 3,446, so the table draws the top '
    + '200 under the sort and says so in the header; IV pct joins the model store\u2019s committed '
    + 'top-1000 and prints \u2014 with the reason below the cut; Save as screen is drawn disabled with '
    + 'the reason on it \u2014 the saved-screen store (6A) waits on the Owner\u2019s schema sign-off, and '
    + 'the design\u2019s own button only flashed a toast; the Copilot ask replaces no drawn draft here '
    + '(the design has none on this page). Owner to look before aligned.',
  '/research/lab/symbol':
    'Built 2026-09-24 against Research Symbol Method.dc.html at route rev 2026-09-20.4, on local '
    + 'DEV (:5173). Measured first: /vol-surface/fit answers nine expiries of full SVI params and '
    + '/vol-surface/residuals a hundred strikes per expiry, and the store\u2019s parameterisation was '
    + 'pinned numerically before a slider was drawn \u2014 iv_fitted = \u221a(w(k)/T), T = dte/365, total '
    + 'variance, reproduced to 4 dp. Built: the Surface tab with the five raw-SVI sliders seeded from '
    + 'the committed fit (refit drops the hand fit; a store value outside the design\u2019s range widens '
    + 'the range, not the fit), both no-arbitrage lamps, the 620\u00d7190 residuals chart and near-money '
    + 'table with chain-OI weights joined from the vendor snapshots (the residual store carries no OI); '
    + 'the What-if tab with the design\u2019s own cell formula, archetype signs and grid colouring, and a '
    + 'real Save-as-hypothesis through useCreateHypothesis; the Method tab\u2019s six-assumption ledger '
    + 'transcribed whole with measured/assumed badges. The verdict strip cites the lens registry '
    + '(iv_rank \u00b7 vrp \u00b7 skew) and never recomputes. Diverged, named: the strip\u2019s fourth figure is '
    + 'labelled IV30 \u2212 RV60 because that is the store\u2019s own pairing (vrp_60d), not the design\u2019s '
    + 'IV30 \u2212 RV20; spot and change are closes marked at close (no live quote on this face); the '
    + 'window RMSE is computed over the \u00b10.20 window the table shows and the store\u2019s own fit_rmse '
    + 'over all strikes is quoted beside it in the same units (the store writes an IV fraction; \u00d7100 '
    + 'once). Measured finding the badge now shows honestly: the store\u2019s fits are rough \u2014 params sit '
    + 'at optimizer bounds (\u03c1 \u2192 \u22121, m \u2192 \u22121, \u03c3 \u2192 0 on several names) and near-money RMSE runs 4\u201320 '
    + 'vol points because 130+ unweighted strikes include k = \u00b11.5 wings \u2014 which is exactly the '
    + 'chasing-the-wings failure the design\u2019s residNote warns about, on the fit engine itself; the Surface aside\u2019s calibration- '
    + 'window segment is not drawn there \u2014 percentiles are cited, never recomputed here, so the '
    + 'control lives only in the ledger where its effect is named; the event-in tile keeps its place '
    + 'and says no forward event store is on the plan; the Copilot draft panels become AskCopilot '
    + 'with the tab\u2019s snapshot (no draft store); j/k symbol stepping and 1\u20133 tab keys are not '
    + 'carried \u2014 fixture roster, and the shell owns keys. Owner to look before aligned.',
  '/research/lab/history':
    'Built 2026-09-24 against Research History Method.dc.html at route rev 2026-09-20.4, on local DEV '
    + '(:5173). The prototype simulates its bars with an AR(1) generator calibrated to the reading; this '
    + 'side runs the same estimators on the store\u2019s real OHLC \u2014 the bars endpoint carried '
    + 'open/high/low all along and the app\u2019s mapper was dropping them, which is the one API-layer '
    + 'change this walk made. Built: the five method controls with the design\u2019s own notes '
    + '(close-close / Parkinson / Garman\u2013Klass \u00b7 252/260 \u00b7 overlapping or not \u00b7 linear / nearest '
    + '/ Hazen \u00b7 tenor), the Same-IV30-different-answers table across 3m/6m/1y/2y with the spread it '
    + 'exists to show, the sample panel with the honest effective-n line, and the cone under the chosen '
    + 'method \u2014 drawn by the reading face\u2019s own VolCone, which moved to components/research when '
    + 'this face became its second reader (\u00a714.2), its ConeRow moving with it; ivHistory (the old '
    + 'historyModel) moved to utils the same way for the committed reading. The committed verdict line '
    + 'quotes the vrp store through the same ivReading the reading face uses \u2014 same source as trade, '
    + 'suspects withheld \u2014 and the page refuses to run when the store holds no IV30 it stands behind. '
    + 'Diverged, named: the range estimators refuse a window missing OHLC rather than degrading to '
    + 'close-to-close under the wrong name; rank and percentile stay unclamped (outside the sample '
    + 'reports as outside); the Copilot draft slot is not drawn \u2014 no store, and unlike the candidates '
    + 'page there is no seat the design reserves beyond a paragraph. Owner to look before aligned.',
  '/research/lab/today':
    'Built 2026-09-24 against Research Stock Ratings Method.dc.html at route rev 2026-09-22.6, on '
    + 'local DEV (:5173). Measured before building, on the plugin proxy base (the trade-api base 404s '
    + 'the fusion routes): sepa/model/candidates answers 30 rows with grade, stage, path, tech n/11, '
    + 'fund n/8, composite, momentum, IV percentile and PCR; orchestration/status carries the nightly '
    + 'job\u2019s verdict, last run and next tick; candidate-outcome/summary settles 1d and 5d horizons '
    + 'over 90 days; universe/reach names the scan layer\u2019s count; the gex_regime exhibit holds '
    + 'zero_gamma and spot. Built: the batch strip (METHOD badge \u00b7 ASOF from the store\u2019s own '
    + 'trade_date \u00b7 last run \u00b7 next tick), the design\u2019s four states judged from the orchestrator '
    + '(live \u00b7 empty-with-funnel \u00b7 failed-holding-yesterday \u00b7 loading), the funnel from the four '
    + 'stores that own its steps, the hero card (chips, evidence tiles, the two doors, Ask Copilot with '
    + 'the queue snapshot), the ranked rows that re-anchor the hero, and the foot line. The \u29c9 switch '
    + 'on Ratings \u00b7 Stocks lit by itself the moment this route existed, which is what its comment '
    + 'promised. Diverged, each named: the prototype\u2019s scenario segment (Live / Empty / Batch failed) '
    + 'is its own fixture switcher and is not drawn \u2014 the state comes from the orchestrator or it is '
    + 'not a state; the Forecast and Same-setup tiles keep the design\u2019s dash with the reason (no LLM '
    + 'forecast store, no per-setup backtest store \u2014 the funnel carries the source-level record the '
    + 'outcome store does hold, at its own 1d/5d horizons rather than the design\u2019s 20d); the Copilot '
    + 'draft panel keeps its seat empty and says why (the engine\u2019s drafts are hypothesis reviews, '
    + 'not candidate briefs); the hero\u2019s momentum is the model\u2019s own 0\u2013100 score labelled MOM, '
    + 'not the prototype\u2019s 20-day percent, because no 20d move rides the candidate row and a '
    + 'percent invented from closes would be a second computation; RS and the earnings / revisited '
    + 'flags have no store and are not drawn; GEX flip is measured for the hero only \u2014 one exhibit '
    + 'call, the same store the Symbol Dealer face reads. Max pain is not computed anywhere, so the '
    + 'fifth tile is PCR (OI) under its own name. Re-walked 2026-09-25 side by side with the prototype at :8099 after the Owner flagged the density gap: the hero now carries the company name (SEPA wide join), a real 20d momentum from the store\u2019s own closes (one multi-symbol bars read for the queue), the RS chip (crs_percentile) and a hero-size score; queue rows carry RS, 20d momentum, THIN CHAIN where the option face is unmeasured, and the settled hit record per name (candidate-outcome rows grouped client-side \u2014 \u201cunsettled\u201d when none); Add to watchlist is a real write (postWatchlistItem, verified add + delete on DEV); Ask Copilot moved into the hero action row. Owner to look before aligned.',
  '/research/symbol':
    'Walked 2026-09-14 against Research Symbol.dc.html (REDO); my legs, since-you-looked, Plan this and the Structure panel built. Owner signed off on STG 2026-09-15. Re-stamped on Rev 2026-09-15.5 (no construction change to the page). Re-stamped on Rev 2026-09-17.1 (§14.7 colours only: green / red direction, unrealized orange, applied in e05dce2); Owner re-signed after the colour look 2026-09-17. Rev 2026-09-18.2 replaces the header keys with the six verbs, adds the Your verdict panel and seats you · hand verdicts in the Record table, so the sign-off reads stale; the verdict panel and record row are W2, the verbs W3.'
    + ' '
    + 'RE-WALKED 2026-09-21 against Rev 2026-09-18.2, prototype beside the app at one viewport. The '
    + 'first thing the comparison said was about the top of the page: the design opens with the name '
    + '\u2014 `PLTR \u00b7 156.90` and one line of verdict over `3 of 8 lenses decisive` \u2014 and this side opened '
    + 'with the word \u00abSymbol\u00bb and a chip strip. The page said what it was, not what it had concluded '
    + 'about the name in it. **`SymbolIdentity` is that line**: ticker (linking to the name in the '
    + 'book), last price, the decisive lenses in their own words, and the count. '
    + 'Three things it deliberately does not print, each measured: the **company name** is in none of '
    + 'this app\u2019s market payloads; the **change %** cannot be computed because the quote carries '
    + 'bid/ask/last/mid and no previous close, so the figure says `last` and stops; and the design\u2019s '
    + 'one synthesised sentence (\u00abSell premium bias\u00bb) is not synthesised here \u2014 nothing on this side '
    + 'composes lenses into a stance, and writing one would put a judgement in the app\u2019s mouth that no '
    + 'lens made. The decisive lenses are listed instead. '
    + 'THE RIGHT RAIL, item by item. **Since last snapshot** is already here as a strip under the '
    + 'header (`SymbolSinceSnapshot`). **Record on this symbol** is already here as the Validation '
    + 'face, which says which lenses have a settled record on this name and which read all symbols \u2014 '
    + 'the same reading, in a face rather than a rail. **Your verdict** is blocked and measured: '
    + '`/research/symbol-verdicts` answers 404, there is no verdict store, and that is the same hole '
    + 'the Pipeline census recorded as `symbol_verdict` owed. Recording a verdict is also what the '
    + 'deferred six verbs would settle, so both wait on one thing. '
    + 'The prototype\u2019s seventh tab, **Payoff**, is not missing: an earlier round folded it onto the '
    + 'Chain tab\u2019s structure panel, which reuses the portfolio risk-profile engine rather than '
    + 'standing up a second payoff maths. That decision stands and is named here so the tab count '
    + 'difference is not read as a gap. '
    + 'SECOND PASS the same day, on the Owner\u2019s read (\u300c\u548c Design \u7684\u8bbe\u8ba1\u5dee\u8ddd\u6709\u70b9\u5927\u300d): the identity '
    + 'line alone was not the page. The design\u2019s Overview is six panels of dense rows \u2014 '
    + '`IV rank (1y) 71 60% \u00b7 60% n17` \u2014 and this side printed the band\u2019s word with two sentences '
    + 'under it, which reads as prose where the design reads as a sheet. **The one thing missing '
    + 'was the number the lens produced**, and it was in the payload all along: measured on DEV, '
    + 'every exhibit carries `verdict.value` with its own `unit`, and `track_record.by_side` carries '
    + 'both hit rates with their samples. '
    + 'A row is the design\u2019s four columns now: lens \u00b7 reading \u00b7 `5d% \u00b7 20d%` \u00b7 `nN`. '
    + '`lib/lensValue.ts` formats a reading by its own unit (a percentile as a whole number, vol '
    + 'points signed, a share of spot as a percentage) and refuses to guess a scale it does not '
    + 'know \u2014 a wrong scale is worse than an unfamiliar one. Each rate keeps its own denominator, '
    + 'the rule the long record line already followed. '
    + 'What moved rather than went: what a reading **means** is the panel headline\u2019s job and stays '
    + 'on every row as its title \u2014 one hover, where the long record sentence already lived. A lens '
    + 'that did **not** answer keeps its sentence on screen, because an absent reading has to say '
    + 'what is missing. Measured after: Volatility reads `IV Rank 20 \u00b7 58% \u00b7 67% \u00b7 n9`, '
    + '`IV-RV Spread 39 \u00b7 70% \u00b7 73% \u00b7 n15`, `OpEx pin 9.9% \u00b7 68% \u00b7 63% \u00b7 n24`. '
    + 'THIRD PASS, same evening, on the Owner\u2019s read again (\u300c\u8fd9\u4e2a\u548c Design \u7ed9\u7684\u5dee\u8ddd\u6709\u70b9\u5927\u5427\u300d): the '
    + 'rows were right and the **page** was not. What the two screenshots said side by side was '
    + 'structural \u2014 the design\u2019s Overview is two columns, six face cards and a rail, under a tab '
    + 'strip that divides the header from the body; this side had the tabs as one control among the '
    + 'header\u2019s buttons, no rail at all, and four page-level strips stacked between the title and '
    + 'the body so the cards began below the fold. '
    + 'THE FACES WERE CUT ON THE WRONG AXIS. They were the blueprint\u2019s six questions \u2014 Trend, '
    + 'Volatility, Positioning, Events, Forecast, Validation \u2014 and the design cuts them by the '
    + 'faces this page already has tabs for: Trend & structure \u00b7 Volatility \u00b7 Dealer levels \u00b7 '
    + 'Scenario \u00b7 Flow \u00b7 Events, each card a preview of the tab it opens. So Positioning split '
    + '(dealer gamma and order flow are two tabs and two questions \u2014 a card previewing two tabs '
    + 'cannot have an Open), Forecast took its tab\u2019s name, and **Validation left the grid for the '
    + 'rail**: it never had a lens of its own, it read every *other* lens\u2019s record, so as a card it '
    + 'repeated its neighbours. Ranked in the rail as `Record on <sym>` it answers the one question '
    + 'the cards cannot \u2014 of everything with an opinion on this name, which has been right. The '
    + 'blueprint\u2019s questions survive as each card\u2019s hover: the cut changed, the questions did not. '
    + 'THE CARD IS THE DESIGN\u2019S THREE PARTS NOW: a header that says where the face is read in full '
    + '(`Dealer tab \u2192`, and the link is this page\u2019s own tab), then a **verdict block** \u2014 colour '
    + 'bar, verdict, and one line of what it means \u2014 then the rows. The means line was missing '
    + 'entirely: the card said what it found without saying why that matters. '
    + 'EVERY NON-LENS ROW THE DESIGN DRAWS WAS ALREADY IN THE PAYLOAD, which is the measurement that '
    + 'made this pass cheap. `Walls 145 / 165` is `gex_regime.readings.major_put_wall` / '
    + '`major_call_wall`; the GEX flip is `zero_gamma`; `Close expectation` is '
    + '`terrain_regime.readings.expected_close`; `Structure \u00b7 VCP` is `sepa.readings.structure_score`; '
    + 'the OpEx count is `opex_pin.readings.dte` with its `expiry`. None of them costs a request. One '
    + 'does and gets it \u2014 `SEPA trend template 9 / 11`, because the exhibit carries the percentage '
    + 'and the repo already ruled that the count must be read from `tech_pass_count` rather than '
    + 'divided back out of a score. '
    + 'THE HEADER IS THE DESIGN\u2019S: `VERDICT` over the decisive lenses\u2019 own words, then '
    + '`n of m lenses decisive \u00b7 volatility drove the rating \u00b7 watchlist only`. **Drove the rating '
    + 'is the list\u2019s claim, not this page\u2019s** \u2014 a ranked table is an opinion about one thing, and '
    + 'only the table knows why it sorted, so both ratings pages now publish it on the trail along '
    + 'with the design\u2019s `WHY IT WAS THERE` chips (`composite 47.8 \u00b7 IV rank 33 \u00b7 VRP 57 \u00b7 '
    + 'terrain range`) and the weights they ranked under. The chips are the list\u2019s own numbers, '
    + 'formatted by the list, so the strip cannot disagree with the table you came from. '
    + 'CORRECTED FROM THE LAST PASS: **`/research/verdicts/{symbol}` is not 404.** The earlier note '
    + 'said there was no verdict store; the route exists, this app already reads it in the Copilot '
    + 'strip, and it answers with every claim the Copilot and the Loop have made on the name with '
    + 'its approval state. What is missing is narrower and sharper: the route is GET only '
    + '(`symbol_verdicts.py` declares one read) and no route in the research API accepts a stance. '
    + 'So `Your verdict` draws its lower half for real \u2014 the claims and their states \u2014 and says '
    + 'the form is not drawn because a Record button that kept nothing would be worse than the '
    + 'sentence. It offers a hypothesis instead, named as a different artifact rather than a '
    + 'stand-in. '
    + 'TWO MORE THINGS LEFT rather than were added: the **Copilot strip** leaves Overview (the rail '
    + 'now lists the very claims it summarised, with their states) and the **symbol picker** leaves '
    + 'every face but the two that need the as-of date beside it \u2014 the shell\u2019s own field sets the '
    + 'symbol and stays on the page, so a second box under the tabs was a second way to do one '
    + 'thing. Both stay where they are the only voice. '
    + 'Marked, not faked: the six read-artifact verbs (no artifact store, Owner deferred); the '
    + '`snapshot today / \u22121d / \u22125d` control (`/research/exhibit` takes no `as_of`, so a prior '
    + 'reading cannot be asked for \u2014 Since-last-snapshot compares against the last reading this '
    + 'browser saw instead); `Earnings` (no forward calendar reaches this side); `Forecast 30d hit` '
    + '(a record for a lens that returns no reading on any name, and its row already says so); '
    + '`Vol / OI top strike` (a per-strike reading that lives in the chain \u2014 Flow shows the two '
    + 'put/call ratios it does carry instead). '
    + 'The record rail\u2019s own honesty: it ranks by 20-day hit rate on the side each lens sits on, '
    + 'ambers a thin sample without moving it down the order (a 100% on n=9 genuinely tops the rate '
    + 'column; hiding it in the sort would hide the sample), and says how many of the records are '
    + 'this name\u2019s own \u2014 on MRVL two of five are, the rest answer `symbol_scoped: false` and are '
    + 'pooled across the universe. '
    + 'Swept: `1`\u2013`6` switching faces, `j` `k` stepping the list, the six `Open` links landing on '
    + 'their own tabs, the four capture verbs, the chips, the rail\u2019s claim list. No horizontal '
    + 'overflow at 1024 or 1600; the whole Overview fits one viewport at 1600. The chip tones took '
    + 'the P&L tokens at first and `check:legacy-css` caught it \u2014 \u00a714.7 \u2461: a bordered chip takes '
    + 'a lamp colour, and a hot lens is not a loss. Owner signed off 2026-09-23 on local DEV (:5173) at this rev. '
    + 'GREW ITS SEVENTH FACE 2026-09-24: Payoff, the tab this side had deliberately withheld while '
    + 'there was no data behind one — the vendor’s snapshots now carry iv and delta per contract, '
    + 'measured on DEV before building (NVDA 2026-10-16: 160 rows, 131 with greeks). Built against the '
    + 'prototype’s isPayoff section at the design’s own /research/payoff rev (2026-09-17.1): the '
    + 'structure bar (Single / Vertical / Covered-CSP × Short / Long, legs chips, the from-Chain / '
    + 'default-Δ source label), the P/L chart with the expiry line, the dashed today line (BS, IV '
    + 'unchanged), ±1σ/±2σ bands from the contract’s own IV, spot in the ticker colour and the '
    + 'break-even; max profit / max loss / loss at −2σ / break-even / P(profit) / margin estimate / '
    + 'return on margin / θ·Δ; the Scenarios table at the band’s own marks with lognormal '
    + 'probabilities; Greeks by spot at ±5% steps; Plan this structure; and → Hypothesis, a real '
    + 'createHypothesis write with the structure’s claim (verified on DEV and the test record retired). '
    + 'ONE PAYOFF ENGINE, as the Chain panel’s own rule said: the expiry line and its stats are '
    + 'riskProfile’s (`payoffOptionsAtPrice` / `computeRiskProfile`); BS prices only what an expiry '
    + 'engine cannot — time value. The chain helpers (`chainFromSnapshots`, `pickExpiry`, `isMonthly`) '
    + 'moved to utils/optionChain when this face became Compare’s second reader (§14.2), gaining an '
    + '`iv` field. The Chain tab’s inline Structure panel — built 2026-09-14 as the stand-in for this '
    + 'very tab — retired into it: everything it could do is here with more, and its spot under the '
    + 'chain is now the hand-off strip that opens this face on the selected contract (§15: relocated, '
    + 'not dropped). Diverged, each named: the design leans on the Chain face’s expiry state, which a '
    + 'remounting tab cannot share, so the hand-off rides the URL (?expiration=&strike=&right=) and the '
    + 'face carries its own expiry select defaulting three weeks out; the design’s earnings-gap '
    + 'scenario rows need a forward earnings date that is not on the data plan, so none is drawn and the '
    + 'footnote says so; the CSP’s short-stock marker is not drawn because the one payoff engine '
    + 'prices a cash-secured put without a stock leg, and a chip must not claim a leg the chart does not '
    + 'price; marks are EOD closes and the header says `at close`, the same honesty Compare carries. '
    + 'Observed while walking, not this face’s to fix: the Chain tab’s quotes table reads the '
    + 'Trade-side option_snapshots store (empty on DEV until a snapshot job runs), while this face and '
    + 'Compare read the plugin catalogue — two sources for one chain, recorded as debt. Swept: the '
    + 'redirect (/research/payoff → ?tab=payoff), the deep link with strike & right (from Chain · '
    + 'change →), the default label (default Δ 0.26 put · pick in Chain →) landing on the Chain '
    + 'tab, all three structures and both sides against DEV numbers (short put 215: BE 212.07 = strike '
    + '− credit, max loss = strike×100 − credit; vertical 212.5/215: +$56 / −$194 = width − '
    + 'credit), no horizontal overflow at 1024. Owner to look before aligned.',
  '/research/scan':
    'Walked 2026-09-21 against Research Scan.dc.html (Rev 2026-09-20.10) — the option side of '
    + 'Stock ratings, and deliberately the same page twice. What stood here printed the weights '
    + 'as a sentence (iv:25 vrp:25 slope:15 …) under a row of five lens chip filters: the model '
    + 'described rather than handed over. It now has the design’s left rail — Composite · '
    + 'Weights with the four preset tabs and five sliders, and the Tape panel — and the design’s '
    + 'own Why inspector on a row click, with j k esc. '
    + 'MEASURED FIRST, because the sliders only mean something if they can move the ranking: '
    + '/research/scan takes a **preset** and no per-weight parameter, so the composite is '
    + 'recomputed on this side from the same row fields the engine reads (iv_rank_1y and '
    + 'vrp_pct_252d are already percentiles; the slope and pin distance go through the engine’s '
    + 'own 50 + clamp(x × 200, ±50); terrain scores on pin_score). Recomputing all 500 DEV rows '
    + 'at the server’s neutral weights reproduced its composite_score exactly — max difference '
    + '0.0 — and again at the momentum preset over the 472 rows both windows share. So the page '
    + 'opens agreeing with the server and the Why panel can print both numbers; the points sum '
    + 'to the composite. Adapt is the server’s own fitted set, fetched rather than written down '
    + '(adaptive_30d is 30 days of lens hit rates, ~40ms for one row), and it is the reason a '
    + 'weight box prints 17.4 rather than 17 — rounding the fitted set would show a model that '
    + 'is not the one being applied. '
    + 'TWO NAME TRAPS, both measured: pin_score is **not** the pin lens — it comes from '
    + 'stock_forecast_terrain_daily beside regime and feeds the terrain component, while the pin '
    + 'lens is pin_pct_distance from the OpEx table; and terrain always counts, because the '
    + 'engine substitutes 50 for a null pin_score, so its weight stays in the divisor while a '
    + 'lens the row genuinely lacks (IV rank on 38 of 500) leaves both halves. '
    + 'EXTRACTED RATHER THAN COPIED (§14.2): the weights panel, the tape panel and the lens bar '
    + 'cell are one implementation in components/research/, read by both ratings pages. Two '
    + 'ranked lists one click apart that ranked or drew differently would teach the reader '
    + 'nothing they could carry between them. The Stocks page was re-pointed at the shared three '
    + 'in the same pass and re-checked beside its prototype. '
    + 'BETTER HERE THAN ON THE SIBLING, and worth saying because the sibling marks both as owed: '
    + 'the Rule column is real — strategy_opportunity rows carry a symbol list, so the cell '
    + 'names the active opportunity registered on a name and deep-links its chain at '
    + '/trade/rules?pick=opportunity:<id> (7 active covering 15 symbols, 14 of them in the '
    + 'scan’s 500). What it still cannot say is that the entry conditions are *met*: nothing '
    + 'evaluates those per name. And the capture ladder is drawn in full — pin · pool · '
    + 'hypothesis · plan — because all four already had somewhere to write. A pin from here is '
    + 'an iv hit stamped /research/scan, the same shape and origin the Pipeline census stamps, '
    + 'so the same name captured from a lane lands as one row rather than two. '
    + 'THE H1 STAYS “Vol ratings”: the prototype’s header still reads “Ratings · Underlyings”, '
    + 'but the design’s registry renamed this leaf when it flattened the two false Discover '
    + 'folds — four leaves, machine short names, ≤13 characters — and §5a.5 ties the h1 to the '
    + 'route label and the last crumb. '
    + 'Marked, not dropped: Earn (no forward earnings date reaches this side — '
    + '/research/events/calendar answers count 0 and the gap behind it is a vendor '
    + 'subscription; the design’s “veto a rule inside 10 days of a print” is the same absence '
    + 'twice); the per-lens 252-session band behind each bar (the row carries today’s reading '
    + 'and none of the lens’s history, so the bar is the score on its own scale); the Screen '
    + 'chip (nothing saves a screen yet, the same gap the Stock screen page names); and '
    + '“→ Autopilot objective”, which writes a standing schedule and whose source stamp is the '
    + 'same open product question the Stocks page carries. '
    + 'Kept though the design does not draw them: Ask Copilot, whose snapshot is this page’s own '
    + 'numbers, and the symbol trail the Symbol page reads to say “From Underlyings · 3/19”. '
    + 'Elsewhere rather than gone: the five per-row Labs links moved into the Why panel — the '
    + 'prototype’s own footer says so — and CompositeRegimeRibbon, a per-symbol reading, stays '
    + 'on Symbol where it belongs. '
    + 'Swept: 19 rows on DEV at Both, both segment controls into the URL, four preset tabs, a '
    + 'slider to Custom (Σ 130, and the divisor is the applied weight so the ranking stays '
    + 'valid), the row click into ?sym=, j k walking one step each way, esc clearing it, the '
    + 'Rule link, the symbol link, and the four verbs. No horizontal page overflow at 1024 or '
    + '1440; the inspector docks at 1600 and floats at 1024, per the one dock formula. '
    + 'At the server’s own weights nothing in the book clears 70, so Hot is empty and the tape '
    + 'reads Mixed — reachable by moving the weights, which is the page’s point. Owner signed off 2026-09-23 on local DEV (:5173) at this rev.',
  '/research/ratings/stocks':
    'Built from nothing 2026-09-21 against Research Ratings Stocks.dc.html, then re-walked the '
    + 'same day after the Owner read it beside the prototype: the colour was off and the ranked '
    + 'list was too long. Both were real, and the second was the worse of the two. Measured '
    + 'before building: /research/sepa/model/daily returns 500 rows carrying four component '
    + 'scores per symbol — trend_template_score, fundamental_score, momentum_score, '
    + 'structure_score — and, in factors_json, **the weights the server combined them with** '
    + '(trend .35, fundamental .30, momentum .20, structure .15). sepa_score is that combination '
    + 'and it reconciles, so the sliders recompute the same number rather than decorating it, '
    + 'and the page opens agreeing with the server. The Why panel takes it apart: points are '
    + 'score × weight over the weight actually applied, and they sum to the composite. '
    + 'THE LENGTH: the first build drew all 500 in one list. The design has a filter bar and the '
    + 'app had skipped it. Universe reuses usePortfolioSymbols (the same holdings/watchlist '
    + 'membership the PortfolioTag reads, so the chip and the filter cannot disagree) and '
    + 'defaults to Both — nine names on DEV rather than five hundred. Show is the design’s '
    + 'hot/cold at 70 and 35, and it is worth knowing that cold is reachable only by moving the '
    + 'weights: at the server’s own the composite floors at 47.9 and 0 of 500 are cold, while '
    + 'Quality-led puts 62 there. Both counts are read off the universe you chose, so they are '
    + 'the denominators of the list underneath. The list stops at 200 rows and the title says '
    + '“200 of N” when it does. THE COLOUR: the lens cells drew a solid bar filled to the value '
    + 'in green or red, which put four columns of saturated colour across every row and left the '
    + 'tags and grades competing with it; the design draws a quiet track with a thin accent '
    + 'marker and colours only the number, and so does this now. Grade · path is coloured by '
    + '**path** rather than grade, which is the design’s own choice and a different reading — '
    + 'grade splits 15 A / 298 B / 187 C and colouring by it made every A green while saying '
    + 'nothing about whether the name is actionable. The Tape panel went from two columns of '
    + 'tall blocks to the design’s thin row, and gained the verdict sentence it was missing. One '
    + 'colour difference is **not** a gap: the prototype renders its ticker in lime because '
    + '.os-sym hard-codes #a3e635, which its own skin contradicts — shell-registry puts '
    + '/research/* in the analysis layer, whose accent is #60a5fa, and that is what both the '
    + 'app and the prototype’s own tokens resolve to. The app follows the layer. '
    + 'FORM: Trend and Growth now read as counts of checks passed, 11 and 8, because that is '
    + 'what the two scores are — trend_template_score takes only the eleven values n/11 × 100 '
    + 'and 231 of the 500 rows sit at exactly 100, so a column of percentages was a column of '
    + 'hundreds while 10/11 beside 11/11 still says something. The count is read from '
    + 'tech_pass_count / fund_pass_count, never derived from the score: a score without its '
    + 'count stays a score. '
    + 'Marked, not dropped: a relative-strength lens (no RS field on this row, so the Tape has '
    + 'four bars where the design has five); Earn (no future earnings date reaches this side — '
    + '/research/events/calendar, /research/events and /research/event-radar/events all answer '
    + 'with count 0, and the vendor gap behind them is a subscription one); Rule (the store '
    + 'answers and holds nothing today, but the shape is the harder half — a playbook rule '
    + 'carries a title, a category and prose, with no symbol and no predicate, so nothing can '
    + 'decide which rule a row matches); the per-lens 1-year band (high_52w/low_52w are price, '
    + 'not lens history); the saved-screen filter (nothing saves a screen yet, the same gap the '
    + 'Stock screen page names); and the Why panel’s settled record (the outcome store settles '
    + 'candidates the loop nominated, not rows of this list, so there is no prior set to count). '
    + 'Owed, not marked: the row’s Pin / Pool / Hypothesis verbs and the two header buttons. '
    + 'Each writes somewhere — the shelf, the Candidate Pool, the Book, the loop’s schedule — '
    + 'and what this page stamps as the source of a write is a product call, which is the same '
    + 'reason the six-verb row was deferred on 2026-09-21. Plan is built, because it navigates '
    + 'rather than writes and /trade/plans reads both ?symbol= and ?new=1. '
    + 'Interactions swept on local DEV (:5173): 18 links, every symbol to Symbol and every Plan '
    + 'to the Plans desk, both destinations reading their params; rows carry role=button, a '
    + 'keyboard route in and a pointer, and open the Why panel with the name in ?sym= so an '
    + 'argument about one can be sent to someone; Escape closes it and clears the param; links '
    + 'inside a row stopPropagation; no horizontal overflow at 1024 — the table scrolls inside '
    + 'its own wrapper. An empty list names the filter that emptied it rather than showing '
    + 'nothing. One thing this page surfaced and the component fixed: SectionPanel painted its '
    + 'body bg-card, the canvas colour, so every panel was the same shade as the page behind it '
    + 'and the whole page read flat. The design’s panel is a well — body on --sk-ground '
    + '(bg-background), header on --sk-surface (bg-secondary), which exist here value for value '
    + '— and the Owner chose to change the component rather than override it here, so Portfolio, '
    + 'Risk, The Book and Review › Objectives gained the same depth in the same commit. '
    + 'Owner signed off 2026-09-21 on local DEV (:5173) at this rev. '
    + 'RE-WALKED 2026-09-23 against Rev 2026-09-23.6, which is the design answering this side\u2019s '
    + '\u00a715.2 disposition table: SEPA Daily Core\u2019s five capabilities and Momentum Radar\u2019s nine '
    + 'factors land here, every one of them rated \u00abequal\u00bb, so the two pages finally have a '
    + 'destination that is not weaker than they are. '
    + 'THE TWO COLUMNS COST NOTHING, and that is the measurement that shaped the rest: IV %ile '
    + 'and PCR OI are already on `/research/sepa/model/daily`, the one call this page makes \u2014 '
    + '`RawRatingRow` had simply never declared them. On DEV 2026-09-23 both are populated for '
    + '**146 of the 500** ranked names, so the dash is common and means the option side has not '
    + 'reached that name, not that the reading is zero. '
    + 'THE FILTERS FILTER IN THE BROWSER, against the endpoint\u2019s own `stage` / `path` / `grade` '
    + 'parameters, and the reason is the composite: it is computed here from your weights, so a '
    + 'server filter would change the pool the average is taken over and the same slider would '
    + 'read differently under each filter. One fetch, one pool, filters on top. All three are URL '
    + 'state, so a filtered view is a link. '
    + 'THE FINDING, and it changed what the three figures say. The design puts Setup+Pivot, '
    + 'Stage 4 and Avg composite beside the bar. Measured: today\u2019s 500 ranked rows hold only '
    + 'STAGE_2A and 2B, PIVOT / SETUP / WATCH and grades A / B / C \u2014 so Stage 4 reads 0 and the '
    + 'S1 / S3 / S4 / Avoid / D buttons select nothing. Asked directly the endpoint answers with '
    + 'rows for `stage=STAGE_4`, `path=AVOID` and `grade=D` (and genuinely none for `STAGE_3` or '
    + '`EXTENDED`), so the emptiness is this page\u2019s ranking window, not the store. An empty 200 '
    + 'is not an empty set. The figures therefore name their denominator \u2014 \u00abof N ranked\u00bb, with '
    + 'the window spelled out in the title \u2014 and they are taken over the pool rather than the '
    + 'filtered view, because a Setup+Pivot count that changed when you pressed Setup+Pivot would '
    + 'answer a question nobody asked (checked live: 9 and 72.9 hold as the filter cuts 10 rows '
    + 'to 5). `EXTENDED` is not drawn as a sixth path button, since nothing can ever select it. '
    + 'THE FACTORS PANEL is strictly more than the page it came from: this app has never shown '
    + 'these nine values anywhere \u2014 the radar carries the legend that explains them and a card '
    + 'with the score, grade and path, and the sub-scores appear nowhere. Two things had to be '
    + 'measured before it could be built honestly. They are **not z-scores**: the names read '
    + '`z_sdt`, `z_v`, `z_ofi` and the prototype colours them on \u00b11.5, but the engine returns '
    + '0\u2013100 sub-scores, higher better (z_sdt 55\u201385, h_52w 36\u2013100, crash 0\u2013100 over 200 rows), so '
    + 'a `crash` of 0.7 would be the worst reading in the sample rather than an alarm. The panel '
    + 'cuts at 70 / 35 instead \u2014 the same cuts the composite already uses, pinned to `HOT_AT` and '
    + '`COLD_AT` by test, so this page has one rule and not two. And **`z_ofi` is pinned**: its '
    + 'minimum, median and maximum are all exactly 50.0 across 200 rows, so the order-flow proxy '
    + 'is not computed and the engine substitutes the midpoint. It prints \u2014 and says \u00abnot '
    + 'computed\u00bb rather than rendering as a middling reading, which is the same hole Lens '
    + 'Coverage names where `order_sentiment` screens 0 of 647. '
    + 'THE PANEL CARRIES ITS OWN SESSION, and live data proved the design right to ask for it: '
    + 'the ratings read 2026-09-23 while the newest momentum row for every symbol tried is '
    + '2026-09-22. One request per selected symbol \u2014 `?symbol=X` answers with that name\u2019s latest '
    + 'row and nothing else, while asking without a symbol returns the top 200 scores across '
    + 'three months and 102 names, which is not a per-name lookup. A name with no momentum row '
    + 'says so as a coverage fact rather than an error. '
    + 'POOL was owed here on a product question \u2014 what this page stamps as the source \u2014 and the '
    + 'design answered it: source `scan`, carrying grade, path, stage, the composite and the '
    + 'preset it was read at. The \u25ab glyph becomes the real `AddToPoolButton` the radar already '
    + 'uses; Pin and Hypothesis stay owed with the six-verb row. '
    + 'EXTRACTED BEFORE DUPLICATING (\u00a714.2): the nine annotations were prose inside the radar\u2019s '
    + 'legend, and the prototype\u2019s copy came from that same legend \u2014 three copies one edit apart. '
    + 'They now live in `lib/momentumFactors.ts` with the reading rules, the legend renders from '
    + 'it, and the test asserts the radar page contains **no** second copy rather than that two '
    + 'copies agree. '
    + 'DIVERGED: no colour on any factor value. This page colours no unsigned score \u2014 Grade \u00b7 '
    + 'path is a DenseTag and the composite is ink \u2014 and \u00a714.7 keeps the direction hues for '
    + 'signed numbers, so magnitude is a track and strength is weight. Checked at 1680 and at '
    + '1024 (no page overflow; the table scrolls in its own container at 1272 against a 773 '
    + 'main). RE-WALKED 2026-09-23 against Rev 2026-09-23.9, which is the design answering this side\u2019s own ask: Momentum Radar was a **ranking across sessions** and nothing here could hold that reading. The ruling is \u00a715.4 option 1 \u2014 補進設計 \u2014 and the去向表 gains a row rated **stronger** than the page it came from. BUILT: a View at the head of the first filter bar, Today | Leaders, in the URL. Leaders is one request \u2014 `/research/momentum/radar?limit=200` \u2014 folded by name here, because the payload is the top N **symbol \u00d7 session** and `?symbol=` would have been a hundred calls. THE FOLD IS THE READING. Measured on DEV: 200 rows, 102 names, 33 sessions from 02JUL26 to 22SEP26, and 55 names appear more than once \u2014 flat, that reads as a leaderboard repeating itself; folded, each repeat is `Hits`, which is persistence and sorts. The session bar draws one cell per session in the window, filled where the name was on the list and solid by score, and the ramp runs over the window\u2019s own range (72.6\u201386.1) rather than 0\u2013100, because the radar only ever returns its top N and a 0\u2013100 ramp would draw the whole bar at one weight. Clicking a cell reads that session in the factors panel, which is why the panel now takes a `session` \u2014 a cell is a name on a day, and the latest row would answer a question the reader did not ask. THE HEADER SAYS THE WINDOW AND THE LATEST SESSION SEPARATELY, and that is the whole honesty of the view: `latest session 22SEP26: 9 names`. The payload ranks three months by score, so its newest session holds nine names \u2014 a page headed \u00abtoday\u2019s leaders\u00bb would be wrong about 191 of its 200 rows. Leaders opens at Universe \u00b7 All, and the deep link had to be taught the same thing: `?view=leaders` with no universe was reading the book filter, so the link showed 15 names where the toggle showed 102 (found by opening the link). Weights and the tape hide on Leaders \u2014 they act on today\u2019s composite, not on the momentum score \u2014 and the factors panel stays. SPLIT, because the ratchet said so and the design had already drawn the seam: a page with two Views should not hold both bodies inline. `TodayFace.tsx` beside `LeadersFace.tsx`, the page keeping the header, the View and the shared filters (848 \u2192 567 lines, files-over-800 back to 6/6). Three corrections this side reported were adopted by the design in the same round: the nine factors are 0\u2013100 sub-scores and not z-scores, `z_ofi` is not computed, and the weight presets take this side\u2019s names \u2014 the prototype\u2019s SEPA/Mom/Growth/Adapt were Vol ratings\u2019 controls borrowed, and the design agrees the two pages should NOT be aligned into one set, since they are different models on different lenses. Checked at 1680 and at 1024.',
  '/research/screener':
    "Owner ruled 2026-09-20 which of this side's pages the design's Stock screen is, and the "
    + "page took the design's own path with the name. The evidence is the prototype's content, "
    + 'not the label: Research Screener.dc.html is universe -> criteria stages (AND between '
    + "stages, OR inside one, 'at least N of these') -> results -> lineage v1->v2, and only "
    + 'this page has any of the three. Stock Explorer has no criteria of its own; it is a tab '
    + 'shell over SEPA Daily Core, Momentum Radar and Event Radar, all three of which the '
    + 'design redistributed. An earlier note in routeRegistry read the design’s Screener as our '
    + 'Explorer; that reading is withdrawn. The old `/research/stock-screener` address redirects '
    + 'here; `/research/screener` stopped being a redirect to the Option Screener, which means '
    + 'an option-screener bookmark written before 2026-09-15 now lands on a stock screen. '
    + 'First walk against the prototype 2026-09-20, cell by cell, under the interaction '
    + 'standard. Measured before building, on DEV: `criteria-stats` carries a per-condition '
    + 'pass count for the eleven technical and eight fundamental conditions over a universe of '
    + '5319 at eval_date 2026-09-19, plus a pass_count_distribution for each — and that '
    + 'distribution IS the design’s `min` stepper, because “at least N of these” is its tail. '
    + 'So the first two stages are live, chips and stage totals both. The other five are not, '
    + 'and each is marked with its own reason rather than dropped: Momentum and Structure read '
    + '200 with a count of 0 and a note naming dw_stock.mart_sepa_tier_* as awaiting 252+ '
    + 'trading days; Quality returns nothing for all seven of its ids while the same endpoint '
    + 'returns rows for the growth conditions, which is what makes it “no data for these '
    + 'conditions” rather than “the endpoint is down” — that distinction cost a cross-check and '
    + 'is the only reason the row can say which; Catalyst and Options have no screen ids on '
    + 'this side at all. Built: the design’s three columns — the universe rail, the Criteria '
    + 'funnel, and results — with the funnel as the page’s criteria surface. It drives the '
    + 'page’s own filter sets rather than keeping a second copy, so a chip toggled in the '
    + 'funnel is the same selection the apply flow reads. Divergences. Each stage’s number is '
    + 'measured against the universe, not against the stage above it: the prototype runs an '
    + 'intersection down the column, and reading the symbol lists for every bucket in both '
    + 'tails would be up to nineteen requests per click for a number the applied screen already '
    + 'answers. The fall is still visible because both stages are counted against the same '
    + '5319, the header says “universe · narrowest stage” rather than implying one ran into the '
    + 'other, and the footnote states which reading it is. The rail’s Presets and My screens '
    + 'are empty with their reason: nothing saves a screen here, and the design’s two writes '
    + '(Workbench preset, Autopilot objective) both go through a Decision Inbox card that does '
    + 'not exist on this side. Not built, and reported rather than faked: the artifact id and '
    + 'the v1->v2 lineage strip (no artifact store — the same gap The Book’s Journal band '
    + 'names), the Explain provenance panel, Rank by (its target, Stock ratings, is unbuilt), '
    + 'the Capture verbs per row, the “Rule that would take it” column, and the Why-it-passed '
    + 'panel. The page’s earlier arrangement of the same conditions — two hero cards and two '
    + 'collapsible filter panels — is still below the funnel under a line saying so: the design '
    + 'replaces both, but what each carries that the funnel does not (the distribution '
    + 'histogram, the tier cards) is a deletion for the Owner to rule on, not one to make in a '
    + 'walk. Interaction sweep: the min stepper moves the count and was clicked (8 -> 9 took '
    + '1,610 to 1,270, which is the distribution’s own tail); a chip toggles, lights, and '
    + 'raises the page’s filter count; Clear empties it back to “nothing selected”; the five '
    + 'inert stages are disabled and say why on hover rather than looking live. No page-level '
    + 'link is drawn to a destination that does not exist — the prototype’s Method and Journal '
    + 'links have no page here and are left out rather than pointed at something approximate. '
    + 'Owner review 2026-09-20 rejected that first pass on two counts, both correct. **The '
    + 'presets were not missing.** The note had said “no preset store on this side”; three '
    + 'of the design’s four name readings this app already produces, two from pages that '
    + 'work today. The probe that produced the wrong answer hit `/research/sepa/daily`, the '
    + 'screener-wide rank table, which carries no `path` at all — the route the page itself '
    + 'calls is `/research/sepa/model/daily`, and it answers 298 SETUP + 15 PIVOT. The rail '
    + 'now loads them: SEPA Daily Core (313 names) and Momentum Radar (A+ and A) land in '
    + 'Results on a click; Event Radar and Premium seller stay greyed with their reasons. '
    + '**And the Momentum stage was mis-marked.** It had been called dead on '
    + '`momentum-filter`, whose tier mart is still accumulating — but '
    + '`/research/momentum/radar` answers today, so the stage is live and its chips carry '
    + 'real counts. The lesson is in the skill now: a stage is dead only when every source '
    + 'for it is, so a reason has to name the endpoint rather than say “no data”. Those '
    + 'counts are **unique names, not rows** — the radar returns a row per symbol per date, '
    + 'so grade A is 92 rows over 56 names, and every other chip on the panel counts names '
    + 'out of the universe; two chips side by side meaning different things is worse than '
    + 'either being wrong. Grades B and C come back at the route’s 500-row cap and print '
    + 'with a `+`. The review also found the page functionally broken: the funnel selected '
    + 'conditions at the top and the only control that did anything with them was the old '
    + 'Search/Apply bar at the foot of the page, below the fold. `Run → Results` now sits in '
    + 'the funnel’s header beside Clear, runs the preview and applies it in one press '
    + '(`runFilter`, awaited — syncing the two through an effect is where a cascading render '
    + 'starts), and the panel reports how many names landed. Verified by clicking: a preset '
    + 'fills Results with its names, a chip lights and Run fills Results from it. '
    + '**Signed off 2026-09-20 knowing it is not finished.** The Owner’s call: the funnel, '
    + 'the rail and the loop are enough to use, and the rest waits for another round rather '
    + 'than holding the queue. What is still open, so the state does not read as done: the '
    + 'artifact id and the v1->v2 lineage strip; the Explain provenance panel; Rank by, '
    + 'which is blocked on Stock ratings being unbuilt; the Capture verbs per row; the '
    + '“Rule that would take it” column; the Why-it-passed panel; and the four stages that '
    + 'stay marked (Structure, Quality, Catalyst, Options). The page’s earlier arrangement '
    + 'of the same conditions — two hero cards and two collapsible filter panels — stays '
    + 'below the funnel by the Owner’s decision, not by omission.',
}
