/**
 * Design-walk notes · Research.
 *
 * The Research layer’s loop and Copilot. Pipeline’s own rows — the ratings
 * pages, the screens and Symbol — live in `researchPipeline.ts`.
 *
 * One file per layer because the record only grows: the notes are long on
 * purpose, and a single catalogue crossed the 800-line ratchet on the day the
 * Review re-walk was written. Split by the group each page belongs to, which
 * is the seam the reader already has in their head.
 */
export const RESEARCH_NOTES: Record<string, string> = {
  '/research/loop/objectives/:objectiveId':
    'Walked 2026-09-22 against Research Objective.dc.html at Rev 2026-09-20.3, rendered side by side with the app on local DEV (:5173). The page was built from this design and never checked against it, so the walk was a comparison rather than a build — and four of the design’s sections turned out to be missing, each of them missing something real. Built: the ⛨ D10 BLOCKED badge in the header, where the design puts the page’s own constraint; the design’s five KPIs (Next run · Last run · Track record · Spend · Awaiting you) replacing a strip that answered four different questions — last memo rather than last run, cost over 30 days rather than today, and no next run at all, which is the one fact a scheduled machine owes; the PATCH PENDING banner, read off the queue rather than off a flag; Leash standing beside Identity; the run-state filter with its count and its own empty state; and Delete drawn disabled with the API’s reason. Measured before it was built (DEV 2026-09-22). Two objectives exist, one active and one archived (the design fixture has four). Next run resolves from the named schedule slot: SCHEDULES calls daily_open weekdays 13:30 UTC, and daily_eod, weekly and adhoc state no clock time, so they read a marked absence rather than a guessed minute — a made-up time on a page about when a machine acts is worse than a dash. Leash standing is objectiveLeash() from leash.ts, the same model the Inbox aside and the Console panel read; on DEV this objective reads BELOW at 33% on 42 settled against a 45% default floor. Only the fourth condition is measured per objective — agreement, validate and evidence are decided inside a run — so the card says that instead of ticking four boxes off one number. The patch banner is the pending policy_suggestion drafts scoped objective:<id>: 19 of them against this one objective, each carrying current_policy and suggestion, so the diff is computed from the two records rather than stored as a third thing that can disagree with them. The design draws one banner; with a queue this long it leads with the newest and says how many are behind it, because a patch waiting and twenty waiting are different facts about the same machine. Extracted before duplicating (§14.2): leashPct moved into leash.ts so the three surfaces that read a hit rate round it identically — a floor and a record compared at different precisions is how 58% clears 45% and 58% is below 58% land on one screen. The same pass took the fourth copy of str(v: unknown) out of the app and into src/lib/readUnknown.ts, which the ratchet caught the moment this page added it. Owed, and marked in place rather than drawn dead. Pause / Resume has no store: OBJECTIVE_STATUSES is active or archived and the backend answers 422 to anything else, so pausing would have to mean archiving — which is the other thing the design is careful to distinguish, reversible versus retirement. Fork has neither an endpoint that copies an objective nor a column that records a parent, so neither the copy nor the lineage can be written or read; the design’s forked-from line goes with it. Diverged, each with its reason. Journal → opens the Journal plain: the page answers sel=<node id> and an objective is not one of its five stores, so carrying a parameter it would drop would be a dead link wearing a live one’s clothes. Spend is labelled 30 days rather than the design’s today, because the store keeps a 30-day sum and no per-day one — printing a month under a word that means a day is the kind of quiet error the rest of this page exists to prevent. The runs count prints both numbers with the fold named (12 recorded, 27 runs with identical re-runs folded): 27 and 12 are both true and mean different things, and side by side without that sentence they read as a contradiction. Identity stays this side’s form rather than the design’s click-to-edit list — same fields, same write-in-place rule, and a form that says which of its values are unsaved. Two emptinesses were showing at once and now only one can: the table’s no-runs-yet is a fact about the objective, the filter’s none-in-this-state is a fact about the filter, and showing both told the reader the history was gone when it was one click away.',
  '/research/greeks':
    'Walked 2026-09-22 against Research Contract Greeks.dc.html at Rev 2026-09-19.2, rendered side by side with the app on local DEV (:5173). The design gives this route a different subject: every option leg in the book, greek by greek — the per-leg detail behind Risk › Exposure’s aggregates. This side held a chain calculator: pick a symbol and a past trade date, fetch the chain, read greeks per contract with the Black-Scholes derivation behind each row. Both are real questions, so the design’s page leads and the calculator is the second face rather than a deletion (Owner ruling 2026-09-18: absence from the design is not deletion). The strip is not computed here, and that is the design’s own rule — its footer says β-weighted aggregation across the whole book, including stock, is Risk › Exposure’s job and this page never re-aggregates differently — so the strip prints useOptionGreeks’s rollup, the same object Risk › Exposure prints, under Risk’s own captions (Γ · per point, Vega · per vol pt, Θ · per day). Measured before it was built (DEV 2026-09-22). The book holds 15 option holdings over three expiries; netted per contract that is 11 contracts, all short, nine calls and two puts. Nine of the eleven price. The two that do not are both AMD, and the reason is not a stale chain: /market/options/snapshots answers count 0 for AMD at every expiry tried — 2026-10-16, 11-20, 12-18 and 2027-01-15 — while the other eight underlyings answer with today’s capture. AMD is absent from the option snapshot store, not behind in it. Those rows are drawn, marked UNPRICED, and counted out of the totals. Two defects came out of rendering it rather than reading the diff. The first is the walk’s finding and it was latent in a shared hook: the book flattens a leg per account × strategy instance, so one contract arrives up to three times — RKLB 18DEC26 90C does — while useOptionGreeks’s byTicker map is keyed by contract, so the last leg written wins. The totals were never wrong (they sum per leg), but a table drawing one row per holding out of that map showed three RKLB rows carrying one position’s greeks against three different quantities. rollupGreeks now also exposes perShareByTicker — the vendor’s own row, per share, which is a property of the contract and cannot be overwritten wrongly — and this page nets by contract and scales from it, so a row’s Γ matches its own Qty and the strip still equals the rollup because summing per holding and summing per net contract are the same sum. The second: while the chain queries were still in flight every row read UNPRICED, which is the silence-versus-all-clear mistake in a new place; the badge is now suppressed until the fetch settles and the marks line says reading the chains. And the calculator face turned out to have no backend at all: the research engine’s OpenAPI carries no /research/greeks route, and fetchGreeksAvailableDates swallows the 404 and returns [], so the date picker read “— no data —”, which says this symbol has no history rather than this engine has no endpoint. The face now says which it is. Diverged, each with its reason. Γ$ / 1% is not drawn: the design rescales gamma by spot and a percent move, and Risk › Exposure prints position gamma per point — two pages showing one book’s gamma at two scales is precisely what the design’s own footer forbids, so this page prints Risk’s figure under Risk’s caption. Rows are netted per contract rather than drawn per holding, because greeks are a property of the contract and the net quantity; the strip says both counts so neither number is a surprise. The tight line is the trader’s own setting (useCushionThreshold, 3% by default) rather than the design’s fixed 5%, and the panel header states whichever is set; the under-21-DTE half is the design’s and is kept. Only a short leg can be called tight — a long leg near its strike is an opportunity, not an obligation arriving. MODEL rows are not marked: the design distinguishes canonical marks from model fallbacks per Signal Health, and this side’s vendor snapshot carries no such flag, so a MODEL badge would be invented rather than read. The per-row Chain → button is the leg token itself, which is the same destination without an eleventh column on a table already at its width.',
  '/research/watchlist':
    'Walked 2026-09-22 against Research Watchlist.dc.html at Rev 2026-09-18.2, rendered side by side with the app on local DEV (:5173). The page was list management — a Step 1 instruction, a category picker, an add box — and the design’s page is a ledger: names with a thesis attached, under a rule that makes the list one (a watch without a thesis expires in 10 sessions). Built, as the Watching face, in the prototype’s order: the header line and Screener →; Stocks as the design’s seven readings (Symbol · Last · Day · IV rank · Since added · Thesis · Age) with Size → and Dossier →; Contracts with its own seven; and the design’s footer, which is also the D10 line — this face watches and promotes, it does not place. Measured before it was built (DEV 2026-09-22): the watchlist answers 22 rows, every one a stock. Day comes from one /market/bars/benchmark call through the shared resolveDailyBasePrice, so the base is the prior settled close and is_today decides which of the benchmark’s two it is — this page does not invent a second rule. IV rank is /market/analytics/iv-percentile per name (no bulk form: a comma-separated symbol answers “No iv-percentile rows”), pooled four at a time by the fetch the IV Radar already uses; 18 of the 22 answer, and the four that do not — BALI, BINC, PFF, SGOV — are exactly the four filed under Fix Income, so the cell carries “a fixed-income ETF has no chain to rank” rather than a dash that reads like a failure. Thesis is the hypothesis whose symbols[] names the row: 5 of 22 have one (ANET, INTC, MRVL, NNE, NVDA). Extracted before duplicating (§14.2): the Book’s census model moved to src/lib/research/bookCensus.ts, because the census says how many watched names carry a thesis and this page says which — one definition, or the two pages give different answers to one question a click apart. For the same reason the table shows every watched name including the four filed under Sizing: the census counts all 22, and a face showing 18 would disagree with it. Owed, and marked in place rather than dropped: Since added and the contracts’ vs added — nothing records the price or the mid a watch was opened at, and for the eleven rows sourced from positions created_at is when the importer ran rather than when anyone decided anything, so a 200-day return stamped “since added” would be a real number answering a question nobody asked; one entry mark on the watch row would answer both columns. Contracts’ IV and Δ likewise: QuoteItem carries last/bid/ask/mid and no greeks, and the chain has them per contract — a join this page does not make. Real zeros, not gaps: the Contracts section is empty because the watchlist holds no option rows today, and the empty state says so. Diverged, each with its reason. The six verbs row under every stock (_Part Verbs) is owed, not missing — Owner deferred the component until the semantics are settled (2026-09-18). Compare → on a contract is dropped because /research/compare has no page on this side; Chain → leads instead and goes to the Symbol page’s chain tab. Size → carries no ?symbol=: Risk › Sizing does not read one, and the design’s own prototype sends the bare route too. The design’s rows are a fixture and draw no list-keeping, so the categories, the optionable toggle, the option add, the inspector and the removal moved into a trailing cell behind the two promotions rather than being deleted (Owner 2026-09-18: absence from the design is not deletion); the Sizing and Positions tabs are untouched, which is what the design’s own footer asks for. Ages run 27 to 200 days, so every row is past the design’s aging mark — the header says that once instead of 22 rows saying it, which is the same judgment the Book’s panel makes about a dominant cause. A loop-written thesis carries its run id, so the cell clamps to two lines and the tip holds the whole of it.',
  '/research/loop/decisions':
    'Walked 2026-09-13 against Research Autopilot Decisions.dc.html (OLD) and the design response of that day; digest actions, kind colour and the approval strip changed 2026-09-14. Owner signed off on STG 2026-09-15. Re-stamped on Rev 2026-09-15.5 (no construction change to the page). Package 2026-09-19.1 moved the page to Rev 2026-09-18.2 — patch cards with a structured diff and evidence, the six-verb row, the ?card= deep link — so the sign-off reads stale; the re-walk is batch W3 of the Vision plan.'
    + ' '
    + 'RE-WALKED 2026-09-21 against Rev 2026-09-18.2, rendered beside the prototype at one viewport. '
    + 'That package added two things to this page. The first is built: a patch card closes with '
    + '**where it came from** \u2014 `parent \u00b7 \u2026 thread \u00b7 \u2026 Journal \u2192` \u2014 because a merge proposal is only '
    + 'as good as what it was distilled from. `parent` reads the artifact the draft is about by the '
    + 'same rule the Journal reads it (moved to `lib/research/draftProvenance` now that the card is '
    + 'its second reader), and `Journal \u2192` lands on that draft\u2019s own node \u2014 verified by clicking: '
    + '`/research/journal?sel=drf_\u2026`. '
    + '`thread` is empty and says so: measured over the 60 pending drafts on DEV, every one is '
    + 'written by an agent on a schedule (`eod_agent` 56 \u00b7 `harness` 2 \u00b7 `digest_agent` \u00b7 '
    + '`weekly_policy_review`), and nothing on this side distils a patch out of a Copilot thread yet. '
    + 'The field is kept so the line fills itself the day something does. '
    + 'The second is the six-verb row the package put on all four card kinds \u2014 **owed, by the Owner\u2019s '
    + 'option B of 2026-09-18**: the verbs are not built until their semantics are settled, and this '
    + 'walk records that rather than counting it as a gap. '
    + 'Everything else the prototype draws is here and was already: the filter row with its split '
    + 'counts, the digest strip, the four card bodies, the Approve\u2192what line with its negative half, '
    + 'the right rail\u2019s Where approvals land and Leash. Repeats fold as the design asks \u2014 the app '
    + 'lists them under their card with a Dismiss for the batch, where the prototype offers a show '
    + 'toggle. The per-card dial line stays off: the Leash panel states it once for the page, and a '
    + 'second surface for one rule is what the design itself keeps deleting. '
    + 'Owner signed off 2026-09-21.',
  '/research/copilot':
    'Walked 2026-09-13 against Research Copilot.dc.html (REDO), six steps built; Threads Origin / Symbol / Writes / Cost and Ran today next tick restored 2026-09-14. Owner 2026-09-15: three tiles stay dissolved (Design ⑫); Desk is dark-only (R8). Owner signed off on STG 2026-09-15 after L1/L2. Rev 2026-09-18.2 anchors the dock to an artifact (anchored bar under the panel head, verb turns as ordinary assistant messages) and gives Personas a Track record table, so this sign-off reads stale; the dock re-walk is W3, the record table lands with the verdict store in W2. Re-walked 2026-09-22 against Package 2026-09-22.3 (Rev .6). The design retired this page’s own conversation aside — §5a.8’s seventeenth round: a page owns no side column, because “open beside” has one destination. This side never grew that aside: the Desk was always the page and the conversation was always the shell’s, which is exactly the two avatars the design arrived at (the rail opens the Desk, the top bar opens the Thread). What did change is that the Thread stopped being a dock of its own and became a surface — same 440, same push formula, but now it can be sent to a float, it shares the tab strip, and its wide 760 tier retired with the dock.'
    + ' '
    + 'RE-WALKED 2026-09-21 against Rev 2026-09-20.20. Two things moved. The fold ate its Desk row '
    + '(the Trade\u203aDesk rule one level down), which this side had already landed \u2014 the row that '
    + 'remains is the page. And the prototype put the Copilot\u2019s three faces under one header as a '
    + 'sticky TAB STRIP: Today \u00b7 Threads \u00b7 Personas, with counts. Built: `CopilotTabs`, shared with the '
    + 'Personas page. Today and Threads are `?tab=` on this route and Personas is a link, because that '
    + 'is what the design does \u2014 its own `route` is `tab === personas ? /research/agent-personas : '
    + '/research/copilot` \u2014 and \u00a75a.5 then reads each page\u2019s h1 off the route you are standing on. '
    + 'Threads left the column beside the digest for a face of its own; the table is eight columns wide '
    + 'and was reading squeezed. '
    + 'The counts come from the queries that already own them, so the strip costs no request the pages '
    + 'did not make: pending drafts (363 on DEV \u2014 the same queue the Inbox counts), today\u2019s sessions '
    + 'off the standing, and the persona list (9). The persona query moved into `useAgentPersonas` for '
    + 'that second reader rather than being typed twice. '
    + 'Still not built, with its reason unchanged: the design\u2019s **Writes** table (kind \u00b7 change \u00b7 '
    + 'thread \u00b7 result). `/research/copilot/standing` returns three counts and `/research/drafts` carries '
    + 'no chat origin, so the rows cannot be reconstructed \u2014 the tile that counts them stays until that '
    + 'read exists. Kept beyond the design and now partly repeated by the strip: **What it works from**, '
    + 'the only place that says what the Copilot reads *from*. Its fate is the Owner\u2019s to call. '
    + 'Swept: every link resolves, both faces and Personas; no horizontal overflow at the pane width. '
    + 'SECOND PASS THE SAME DAY, after the Owner read it beside the prototype and said the gap was '
    + 'still wide \u2014 the first pass had landed the tab strip and left the body as it was. Rendered '
    + 'side by side (prototype on :8099, app on :5173, one viewport) and rebuilt Today to the four '
    + 'panels the design draws: **Waiting on you** is a panel now, not a heading over a table (cap \u00b7 '
    + 'count \u00b7 scope \u00b7 Decision Inbox on the right edge); **Ran today** and **Writes** sit side by '
    + 'side; **Digest** takes the foot, and its readings table went back behind its toggle \u2014 open, '
    + 'that one panel was taller than the three above it together, which is what made the page read '
    + 'nothing like the design. The header gained the design\u2019s kicker (\u2318J or an Ask on a panel) and '
    + 'its primary action, **New thread \u2318J**, which clears the session and opens the dock \u2014 verified '
    + 'by clicking: the dock opens on a blank thread. `Ask Copilot` stays beside it as the other '
    + 'kind of opening, this page\u2019s own context. '
    + 'The Writes panel now says in words what it cannot draw, instead of a bare count in a tile. '
    + 'THIRD PASS, on the Owner\u2019s read of the digest panel: the design does not print the draft\u2019s '
    + 'prose there at all. It prints columns of `SYM \u00b7 one sentence \u00b7 cite`, where the cite opens the '
    + 'page whose lens produced that sentence \u2014 the reading, not the writing. Built from the payload '
    + 'the digest already carries: each name\u2019s most notable lens reading (a band at an extreme over '
    + 'one that is only leaning; a name whose every lens declined still prints, because \u00abnothing '
    + 'stands out\u00bb is the read and a vanished row would be taken for one never looked at), with the '
    + 'lens\u2019 own page as the chip \u2014 measured: `GEX` on AMD opens '
    + '`/research/symbol?tab=dealer&symbol=AMD#gex`. The lamps and the two ways out moved into the '
    + 'panel header, where the design has them. '
    + 'ONE DIVERGENCE, MEASURED: the design splits the names into **Book** and **Watchlist**; the '
    + 'payload has no such split \u2014 `symbols` is one list with `holdings_status: applied` and '
    + '`candidates` is separate and empty. Splitting it from this side\u2019s own book would be a second '
    + 'source answering a question the digest already answered its own way, so the names are one '
    + 'section that says as much in its note. The split returns the day the digest records it. '
    + 'The prose is not dropped: it sits behind a toggle at the foot, because the draft is what the '
    + 'Inbox approves. '
    + 'Owner signed off 2026-09-21. Stamped at Rev 2026-09-21.1 rather than the .20 this was walked '
    + 'against: Package 2026-09-21.4 moved all three Copilot rows\u2019 rev while changing only the '
    + 'Personas face \u2014 Today and Threads are untouched at .1, so the walk holds and the page would '
    + 'otherwise read stale the moment the snapshot was regenerated.',
  '/research/copilot/trading':
    'Walked 2026-09-15 against Research Copilot.dc.html (The book / all starters). The page is the prompt catalogue; the dock The book group uses the same TRADE_QUESTIONS (C2-c). Owner signed off on STG 2026-09-15 after L1/L2.'
    + ' '
    + 'RE-WALKED 2026-09-21 against Rev 2026-09-21.1, which carried this row along when the package '
    + 'moved all three Copilot revs \u2014 and renamed it. **The page is «Book starters» now**: the '
    + 'design\u2019s own ROUTES word, and \u00a75a.5 keeps the h1 equal to it. «Trading Copilot» read as a '
    + 'second Copilot, which it never was \u2014 it is where the book\u2019s starters are written down. '
    + 'ONE DIVERGENCE, and it is this side\u2019s arrangement rather than a gap: the design treats the '
    + 'route as a deep link that opens the dock on its «The book» starter group, and here it is a page '
    + 'the dock\u2019s own group links to. The reason is that on this side there is one catalogue \u2014 '
    + '`TRADE_QUESTIONS` \u2014 read by both the dock\u2019s empty state and this page, so they cannot drift; '
    + 'the prototype hard-codes four starters in its script. Both sides agree it is not a menu row. '
    + 'Added the one starter the catalogue was missing against the design\u2019s four: **short legs inside '
    + '5% of their strike this week** \u2014 the first question an option seller asks, answerable today '
    + 'from the snapshot and quotes. The other three were already covered by the risk, gates and fills '
    + 'questions. '
    + 'Swept: the Gates fact tile pointed at `/strategy/gates`, which still resolves through the '
    + 'redirect those seven retired pages left \u2014 it opens Trade \u203a Rules now, the page that owns that '
    + 'reading. Every other link resolves; no horizontal overflow. '
    + 'REACHABILITY (Owner asked, 2026-09-21: \u300c\u8fd9\u4e2a\u5728 UI \u4e0a\u6ca1\u6709\u8fdb\u5165\u7684\u94fe\u63a5\u5427\uff1f\u300d). Measured: the only '
    + 'door was the dock\u2019s empty state \u2014 the \u00aball starters \u2192\u00bb link on its book group \u2014 and that '
    + 'group renders on a blank thread and nowhere else, so a reader with a thread open could not '
    + 'reach the page at all. It is not a menu row on either side (`inNav: false` in the design, '
    + 'out of the menu here since 2026-09-14), so the fix is not a row: the Copilot desk\u2019s header '
    + 'carries **Book starters \u2192** beside Daily Brief, which is fixed and always visible. Owner '
    + 'chose this over adding a menu row. Verified by clicking it. Owner signed off 2026-09-21.',
  '/research/orchestration':
    'Built from nothing 2026-09-21 against Research Orchestration.dc.html (Rev 2026-09-21.1), the page '
    + 'Design split out of Personas: whose reading to trust is the trader\u2019s question and stays on the '
    + 'bench; who hands to whom, and what each may call, is the engineer\u2019s and is this page '
    + '(Shell Spec \u00a711.4). The diagram did not change \u2014 it moved, whole, with its triage router, its '
    + 'nine agents, the `handoff` / `as_tool` edges and the batch band. '
    + 'What changed around it: the SDK and transport names left the page head for a **How it is wired** '
    + 'fold at the foot, with the tool server and the `BIFROST_PERSONA_EVAL_AGENTS` switch \u2014 a page a '
    + 'trader opens does not lead with a library name, and which of model or heuristic is running is a '
    + 'deployment reading that stays on System \u203a Status. The D10 lock stayed on the diagram: it is the '
    + 'one runtime fact that changes what the reader may do. '
    + 'Picking an agent here hands the name to Personas as `?agent=`, which that page now reads \u2014 a '
    + 'parameter the destination ignored would be the same dead end as a link to nowhere. '
    + 'SECOND PASS the same day, on the Owner\u2019s word to keep aligning: the four sections the '
    + 'prototype actually has are built. **Chat path** (3 stages) beside **Batch path** (4), each '
    + 'stage with its tag and its sentence; the **Agent as tool** strip \u2014 the four specialists \u2192 '
    + 'Verdict, with why a brief cites four readings and carries one stance; and the **Wiring** '
    + 'table (Agent \u00b7 Role \u00b7 Called by \u00b7 How \u00b7 It calls \u00b7 Path) with the path filter and a live '
    + 'edge count \u2014 measured: All 9 rows / 17 edges, Batch 5 rows / 12. Rows are built by '
    + '`wiringRows` off the catalog, so the table and the bench read one graph. Every row opens '
    + 'that agent\u2019s persona. '
    + 'The diagram is not dropped: it sits behind a fold, **The same graph, drawn**, because the '
    + 'table can be filtered and read row by row while only the diagram shows the shape at a '
    + 'glance \u2014 and two renderings of one graph should not both be the first thing. '
    + 'One divergence, and the gate found it: the design\u2019s runtime fold points at **System '
    + 'Status**, a page this side has not collapsed into one \u2014 the link goes to System \u203a Daemon, '
    + 'which holds that reading here. Owner signed off 2026-09-21.',
  '/research/agent-personas':
    'Walked 2026-09-15 against Research Copilot.dc.html (Personas) plus C2-b Tools/Cannot. Origin sentence and default chip rewritten 2026-09-15 (G2): answers go through triage first; the chip is a page default until then; this page does not pick the live stream. Owner signed off on STG 2026-09-15 after L1/L2. Rev 2026-09-18.2 adds the Track record table — you · hand verdicts beside the four judges, same 20d rule, n<10 amber — so the sign-off reads stale until W2 builds the verdict store and the table over it.'
    + ' '
    + 'RE-WALKED 2026-09-21 against Rev 2026-09-18.2, as the Copilot\u2019s third face rather than a page '
    + 'on its own: the same tab strip the desk carries now sits under this header, with Personas '
    + 'current. The h1 still reads this route\u2019s own label (\u00a75a.5), which is what the design does with '
    + 'three rows landing on one file. The persona list is read through `useAgentPersonas`, one key '
    + 'shared with the strip\u2019s count, so the tab and the page cannot disagree about how many operators '
    + 'there are. Nothing else on the page moved at .18.2. Swept: the three tab links resolve; no '
    + 'horizontal overflow.'
    + ' '
    + 'RE-WALKED 2026-09-21 against Rev 2026-09-21.1, which redrew this face: the flat roster and the '
    + 'Track record table below it became one table, **The bench** \u2014 Agent (business name over its '
    + 'mono runtime id, which is never translated) \u00b7 Role \u00b7 Path \u00b7 May call \u00b7 Settled \u00b7 Hit 20d \u00b7 '
    + 'Agrees \u00b7 Weight \u2014 and the wiring diagram moved to its own page (\u00a711.4). '
    + '**Path** is derived, not a second table: `chat` is a triage handoff, `batch` is the review chain '
    + 'a candidate batch takes (`lib/copilot/agentPaths.ts`, with its own tests), so the bench and the '
    + 'Orchestration wiring table cannot disagree. The two rows you cannot route to are greyed and say '
    + 'why \u2014 Verdict composes, Loop Curator follows a batch \u2014 read from a new '
    + '`AGENT_DIRECTLY_ROUTABLE` in the catalog, because every agent carries the same '
    + '`{ by: triage, kind: handoff }` edge and the graph alone could not tell them apart. Design asked '
    + 'for exactly that rather than two ids in a component. '
    + 'FOUR COLUMNS ARE EMPTY, AND THE REASON IS ONE SENTENCE: nothing records a judge\u2019s verdict '
    + 'against the outcome that followed it. The outcome store attributes a settled candidate to its '
    + 'SOURCE \u2014 where it came from \u2014 which is a different question from who graded it, and the Track '
    + 'record table has said so since it was built. So Settled / Hit 20d / Agrees / Weight read '
    + '`not recorded` in grey rather than 0 (\u00a72.1: grey is not red), and three rows read `not a judge` '
    + 'instead, which is a fact about the role and not a gap. The source-attributed table stays below '
    + 'the bench rather than being folded into it: it answers the question this side can answer. '
    + 'Untouched, as the brief says: the persona markdown editor, the preference slots, the Cannot '
    + 'lines and the D10 lock. Owner signed off 2026-09-21.',
  '/research/daily-brief':
    'Walked 2026-09-22 against Research Daily Brief.dc.html (Rev 2026-09-17.1), and it is the '
    + 'largest mismatch this programme has found \u2014 not a shape, a **question**. The design\u2019s '
    + 'Daily Brief has no symbol at all (`symbol=""` in the prototype): it is the morning\u2019s '
    + 'reading of *the book*, the run\u2019s output kept as a page, \u300ca sedimented conversation\u300d in '
    + 'its own words. This side had built a per-symbol lens dashboard \u2014 a symbol context bar, a '
    + 'verdict strip and nine cards (terrain \u00b7 forecast \u00b7 gex \u00b7 opex \u00b7 iv \u00b7 vrp \u00b7 skew \u00b7 term '
    + 'slope \u00b7 sentiment) for one name on one date. **Every one of those nine is now a row on a '
    + 'Symbol face**, so the page was the Symbol page\u2019s lenses rendered twice with a date picker '
    + 'on top. Owner ruled 2026-09-22 that it goes. '
    + 'MEASURED BEFORE BUILDING, and the measurement is what made the rebuild cheap: the design\u2019s '
    + 'page **is the `daily_digest` draft**, which this app already receives and already renders in '
    + 'the dock. Of the design\u2019s four blocks, two are drawn from the artifact and two are not, and '
    + 'each says which: **The one thing** is the agent\u2019s own `### What changed / needs a decision` '
    + 'section; **Loop** is `loop.{pending,runs,objectives,trust}`, tagged RUN / AWAITING / TRUST; '
    + '**Overnight** is owed (the book\u2019s overnight mark, the fills, the pipeline run and the decay '
    + 'alerts are four other stores, and quoting them here means agreeing with Risk, the Ledger and '
    + 'Signal Health on every number); **Today & next** is blocked by the same vendor gap the '
    + 'Symbol Events card and both ratings pages carry \u2014 /research/events/calendar answers count '
    + '0. The header\u2019s run line is real: `generated_by: digest_agent`, the model and the cost off '
    + '`prose` ($0.0011 on 2026-09-22). `\u27f3 Re-run` is marked, not drawn \u2014 the agent runs on a '
    + 'schedule and no route asks it for another. '
    + 'THE ARTIFACT\u2019S OWN THREE SECTIONS \u2014 the holdings\u2019 readings, the dissents, the resolutions '
    + '\u2014 are not in the design\u2019s four blocks and are not dropped: the design\u2019s page is a summary '
    + 'of a run and this *is* that run, so they render below under `The run`, by the same component '
    + 'the dock uses, with the lifted section taken out so nothing prints twice. '
    + 'What went with the old page, having no reader left: `BriefLensCard`, `lib/dailyBrief`, '
    + '`useDailyVerdict` and `VerdictStrip` \u2014 357 lines of machinery for nine cards that moved to '
    + 'Symbol. '
    + 'ONE CORRECTION TO AN EARLIER NOTE, found on the way out. `/research/daily-brief/synth` \u2014 '
    + 'the endpoint the old page read \u2014 survives with no caller, and it returns a **synthesised** '
    + 'verdict: narrative \u300cAMD trending \u2014 spot 615.52 below E[close] 617.76 (-0.36%)\u300d, a key '
    + 'risk, an opportunity, each with a destination. The Symbol page\u2019s own note says the design '
    + 'writes a synthesised verdict and \u300cnothing here synthesises\u300d; that is too strong \u2014 this '
    + 'does. Whether the Symbol header should read it instead of listing its decisive lenses is a '
    + 'walk decision for that page, and the API wrapper is kept, marked, for it.',
  '/research/overview':
    'Walked 2026-09-19 against Research Overview.dc.html (Rev 2026-09-18.2, the rewrite). Built: the design description with D10, the Inbox-waiting button, the dial strip (four levels with the design wording), three operator cards, the six-station table, the Book panel with birthplace bars, the Today feed and the Health panel (real Dagster schedules). The seat selector is gone — the rail follows the route since 2026-09-14, so a chooser chose nothing; ResearchPostures retired with it. Deliberate divergences, each named in its tooltip: the dial is display-only and reads its level off the Trust grant (armed = L1, not armed = L0) because no dial store exists until W4, so the prototype confirm-bar and setDial control are not drawn; the hand card is grey cell by cell (no verdict store until W2, no screen lineage until W3); the loop card third cell shows the Trust grant instead of the prototype leash-accepted-today count, which no endpoint exposes; station cells count only what stores exist (runs, candidates, hypotheses, pending patches) and the footnote says why the rest are dashes. Kept beyond the design: the Blueprint link (the app route the Vision text has no page for) and LoopOverviewStrip — the is-the-loop-learning circuit has no panel in the prototype; its destination is for the Owner to call. Owner signed off 2026-09-19, after the same look retired the seat rail and set the loop group order. '
    + 'RE-WALKED 2026-09-21 against Rev 2026-09-20.23, which \u00a75a.1 had moved past: the page is now '
    + 'the Research layer itself, and its first section changed shape. The six-station TABLE became '
    + 'the loop drawn as a CIRCUIT \u2014 01\u219203 across the top, 06\u2192405\u2192404 back along the bottom, the '
    + 'violet return edge closing it on the left, and the machines band (the objectives running laps '
    + 'on it, with Console and Their verdicts) inside the circuit rather than beside it. Each station '
    + 'card carries the pages it writes at as chips and the same h / l / c counts the table printed \u2014 '
    + 'one definition, not a second copy (\u00a714.2). \u29c9 marks a page with a Method face and is read from '
    + 'the design\u2019s own FACES table, never listed by hand. Section order follows the prototype: loop '
    + '\u2192 dial \u2192 Today | Health. '
    + 'Two chips the design draws are not links here \u2014 Compare and History, which the design has '
    + 'prototypes for and this side has not built: they keep their place, render plain and say so in '
    + 'their title, because the station writes at four pages whether or not two of them exist here. '
    + 'The Vol ratings chip points at `/research/scan`, not the prototype\u2019s `/research/ratings`, which '
    + 'neither side serves \u2014 the design\u2019s own registry calls `/research/scan` Vol ratings. The machines '
    + 'band prints the status the store keeps (`active` / `archived`); the design draws five states '
    + 'this side cannot mean. '
    + 'THREE BLOCKS KEPT PENDING THE OWNER\u2019S RULING, not dropped (\u300c\u8bbe\u8ba1\u91cc\u6ca1\u6709 \u2260 \u8be5\u5220\u300d): the '
    + 'operator cards (the stations now carry h / l / c themselves and the band carries the loop\u2019s '
    + 'standing \u2014 what has no home in the new shape is the Copilot\u2019s own row), the Book panel '
    + '(`/research/book` is its own page, and aligned) and the circuit strip (is the loop learning \u2014 '
    + 'the prototype has never had a panel for it, here or anywhere). They sit below the design\u2019s four '
    + 'sections until that ruling. '
    + 'Swept: 38 links, every one resolving; no horizontal overflow at 1024; the Vol ratings chip '
    + 'clicked through to a page whose h1 is the chip\u2019s own label. '
    + 'Owner 2026-09-21: all three blocks stay for now \u2014 the ruling is «\u5148\u7559\u7740», not a '
    + 'destination, so they keep their place below the design\u2019s four sections and this note carries '
    + 'the question rather than a silent deletion. Signed off the same day.'
    + ' '
    + 'RE-WALKED 2026-09-22 for the shell restructure (Rev 2026-09-22.2). The page gained a second '
    + 'face and lost four neighbours. **Two faces** (\u00a75a.9): The loop is what this layer is, '
    + 'Pipeline census is what its stations produced, and the switch is a segment control because a '
    + 'face is not a place (\u00a712.2). The route drives it rather than a `?face=` param \u2014 '
    + '/research/workbench is the deep link the design keeps, so it has to be the thing that '
    + 'selects. **Four neighbours** (\u00a75a.8): Autopilot, The Book and the Copilot left the tree '
    + 'for the companion rail, and the Pipeline fold merged into this layer row. What is under '
    + 'Research now is three captions and seven pages at one depth \u2014 the design draws nine because '
    + 'its Analyze has Compare and History, which have no route on this side and so get no row that '
    + 'goes nowhere.'
    + ' '
    + 'PHASE C, the same night: the rail\u2019s icons stopped navigating and started **opening '
    + 'surfaces** (\u00a75a.8 seventh\u2013twelfth rounds). From the rail = floating, from the address bar '
    + '= a page \u2014 the design\u2019s one-line rule. A float is the route\u2019s own component in a window '
    + 'over the page you are on, with three device modes (Phone 420\u00d788vh at the right edge, Pad '
    + 'min(880,76vw) centred, Full 96vw), geometry remembered per route, and **no scrim**: the page '
    + 'behind stays completely interactive, which is the whole claim of the word. Dock semantics \u2014 '
    + 'open IS persistent, the surface rides across navigation until \u00d7 / Esc / the same icon again, '
    + 'and no pin button (the design invented one in the ninth round and retired it in the tenth). '
    + 'NO IFRAME. The design floats `<file>?embed=1#<route>` because its prototypes are separate '
    + 'documents, each needing its own shell hidden. This app is one SPA: the float renders the page '
    + 'component, so the entire embed mechanism \u2014 the flag, the CSS that hides the embedded shell, '
    + '`data-embed`, the `postMessage` remote control \u2014 has no counterpart here and is not built. '
    + 'One consequence is real and stated rather than hidden: **a link inside a float navigates the '
    + 'frame page**, because React Router forbids a second router inside the first. For a spine route '
    + 'that IS the design\u2019s remote-control rule (\u300c\u70b9\u4e00\u4e2a\u540d\u5b57,\u53d8\u7684\u662f\u684c\u9762\u4e0a\u7684\u76d8\u9762\u300d); for an equipment '
    + 'route it is half of it, and closing that half needs the pages to take their route as input '
    + 'rather than read it from the URL. '
    + 'THE RAIL\u2019S FEEL was rebuilt in the same pass on the Owner\u2019s read (\u300c\u6837\u5f0f\u548c\u624b\u611f\u2026\u751f\u786c\u300d), '
    + 'and the first build had made the exact mistake the design had already ruled on: it dropped the '
    + '**whole group** to 40% at rest, where the design\u2019s own comment says *the box is what stays '
    + 'translucent \u2014 the icons keep full ink; dimming the whole group made them unreadable (Owner '
    + '2026-09-21)*. The other half of the stiffness was switching `backdrop-filter` between `none` '
    + 'and `blur(18px)`: the idle state is already glass (5px / 1.15 saturate) and hover only deepens '
    + 'it. Now transcribed rather than paraphrased \u2014 spring curve '
    + '`cubic-bezier(.34,1.56,.64,1)` with the origin pinned to the right edge so the icon grows into '
    + 'the page, the name pill sliding out and counter-scaling to stay 10px, the running lamp a '
    + 'breathing ring rather than an opacity blink, and every hue mixed from the group\u2019s own `--rh`. '
    + 'It is a CSS module for that reason: a rail written as twelve arbitrary-value classes hides the '
    + 'part that matters. '
    + 'One real bug, found by using it: the ResizeObserver could not tell a drag of the corner from '
    + 'the window being laid out, so it wrote the **mode\u2019s own numbers** into the manual-geometry '
    + 'slot \u2014 and since manual beats mode, the next mode click appeared to do nothing. That is the '
    + 'exact failure the design warns about, arriving through a different door; the first observation '
    + 'is a baseline now, not a resize. '
    + 'Not built: Loop Run (no route here, so the drawer has nothing to carry \u2014 the surface exists '
    + 'and a `kind: drawer` flag is all it needs) and scope linkage (the floating Watchlist following '
    + 'the frame page\u2019s symbol), which the design also books for a later round.',
  '/research/workbench':
    'Walked 2026-09-19 against Research Overview.dc.html (workbench view, Rev 2026-09-18.2). The prototype rules the seat home is not redesigned — what changed is around it — so the directory page stands, and the walk adds only the seat-context strip (hand · operator, rail-follows-route sentence). The prototype EmptyState points at Screener Fork lineage and Symbol hand verdicts; both land in W2/W3. Owner ruling 2026-09-19 (Vision §15 Q2, the way §12.3 argued): the seats retire — one tree, Autopilot and the stations standing together — and this page takes the Vision’s own name for them, Pipeline (§12.2: Workbench seat → Pipeline, renamed and de-seated). The current prototype still titles the view Workbench; the rename follows the Vision over the lagging contract, and the seat rail, header chip and ?seat= deep link went with the split. '
    + 'Swept 2026-09-21 under the interaction standard, and it found the worst kind of dead '
    + 'link: every active-hypothesis card’s **Open ↗** pointed at `/research/hypothesis/{id}`, '
    + 'a route that has never existed. The card component carried a comment claiming the link '
    + 'was “graceful even if the route is not yet mounted, because React Router simply renders '
    + 'the 404 boundary”. Neither half held. The route was never mounted, and an unmatched path '
    + 'rendered a **blank document** — no shell, no sidebar, forty-four characters — because '
    + '`errorElement` fires on a throw and a no-match does not throw. Two fixes: the card now '
    + 'opens the Hypothesis Board, which is where a hypothesis is drawn on this side, and the '
    + 'router gained a `*` boundary inside the layout so any wrong URL lands somewhere with a '
    + 'way out. Both verified by clicking. The registry test excludes `/*` with its reason: it '
    + 'is the boundary, not a page, so it wants no label or trail. Everything else on the page '
    + 'resolves, including the two Analyze paths that answer through redirects.'
    + 'Layer reading added 2026-09-21 against Shell Spec \u00a75a.6 (Rev 2026-09-21.2), which gives '
    + 'Pipeline the layer page Risk, Portfolio and The Book already had \u2014 it was the last dual '
    + 'row answering with less than a page. On this side the page already existed (bench '
    + 'directory, today\u2019s work), so the layer\u2019s own reading went **above** it rather than '
    + 'replacing it, the way a layer page leads with the verdict and then shows the detail. '
    + 'The design\u2019s scale is what you made today that has not moved on, and \u201cmoved on\u201d is '
    + 'exact: Distill is the only one of the six verbs that writes, so an artifact you never '
    + 'distilled still sits at the station that made it. '
    + 'MEASURED, AND THE MEASUREMENT IS THE FINDING: **not one station page records what it '
    + 'made.** Ratings and Vol ratings are model outputs the server recomputes daily, with no '
    + 'artifact saying you read one; a Symbol verdict answers with a generated_at rather than a '
    + 'stored row, and a decay check is computed on request the same way; nothing saves a '
    + 'screen, which the Stock screen walk had already settled. Backtest is the single store '
    + 'that keeps a timestamped artifact \u2014 43 runs \u2014 and its newest is 2026-09-06, a '
    + 'fortnight old. Two stores do record a birthplace and neither names a station: '
    + 'hypothesis.origin_page carries only copilot-loop, research-home, candidate_batch_approve '
    + 'and candidate-pool. So **Made has no source either**, which corrects what this side had '
    + 'reported earlier \u2014 the gap had been read as the three states alone. Moved on and the '
    + 'out/wait/cold split rest on the same missing record, and cold (produced and nobody opened '
    + 'it) would additionally need a page-read log, which nothing in this app keeps. '
    + 'Built anyway, with the design\u2019s rows and columns and the numbers marked: Stops here '
    + 'ranks what is true (1 of 7 stations reports anything) instead of what cannot be ranked, '
    + 'and the Backlog names per page the record it would need \u2014 never \u201cno data\u201d. A table of '
    + 'zeroes would have answered a different and false question: that nothing was made today. '
    + 'Absent rather than drawn empty: Oldest untouched (needs an artifact with an age) and '
    + 'Lineage (needs fork records, which the Journal established are kept nowhere). The census '
    + 'is built from BENCHES, the same list the sidebar draws its captions over, so the two '
    + 'cannot disagree about what a station holds. The page header also stopped naming Data, '
    + 'which package 2026-09-20.1 dissolved. Swept at 1500 and 1024: seven rows, each linking '
    + 'to its own page and navigating whole; no horizontal overflow. '
    + 'Rescaled twice on 2026-09-21 in a conversation this side started. The first scale asked '
    + 'what was made today and never distilled; measuring it found that no station page records '
    + 'what it made, and Design changed the scale rather than waiting for a store: **made** is '
    + 'what the station\u2019s engine wrote into a store today, **moved on** is a hypothesis, '
    + 'promotion or pin carrying that page as its origin \u2014 both joins over stores that exist. '
    + 'A second round (ASK-pipeline-2026-09-21) settled three things: screen_run and '
    + 'symbol_verdict were names Design had inferred from page function rather than checked, so '
    + 'those rows read `store owed`; a row may carry Moved on without Made, because origin_page '
    + 'is real on a page that keeps nothing; and coverage is reported beside the stuck share, '
    + 'because a station whose only measurable page is fully stuck shows 100% and that is not '
    + 'the same as being the worst. Four classes on Design\u2019s criterion \u2014 a page owes a store '
    + 'when its product is an object you name again later: has-store (Stock ratings \u00b7 Vol '
    + 'ratings \u00b7 Narrative \u00b7 Backtest), store-owed (both screens \u00b7 Symbol \u00b7 Signal decay), '
    + 'no-store-owed (Compare assembles, History recomputes a denominator) and off-bench '
    + '(Alerts). That criterion is also why the fork lineage cannot be drawn. Measured on DEV: '
    + 'sepa_daily_core 500, option_snapshot_aggregates 500, sentiment_row 100, backtest_run 43 '
    + 'with its newest at 2026-09-06. '
    + 'FIVE BLOCKS FOLDED IN, not dropped (Design\u2019s mapping table, Owner 2026-09-21): the bench '
    + 'directory and the universe funnel are the census\u2019s section headings; the four discovery '
    + 'lanes and the recent backtests open out of the row that produced each \u2014 a lane is the '
    + 'product of a page, so it belongs beside that page rather than in a list of its own; and '
    + 'the active hypotheses are **Left the pipeline**, listed by the station each came out of, '
    + 'which is Moved on\u2019s numerator named. The page is now its header and the census. '
    + 'Marked, not omitted: all five layers of the universe funnel answer `unavailable` here, so '
    + 'Discover\u2019s heading reads `universe not measured` rather than leaving the figure out, '
    + 'which would read as Discover scanning nothing. '
    + 'ONE FINDING WORTH ITS OWN FIX, NOW FIXED (Owner 2026-09-21): **Moved on read zero on '
    + 'every station row and the join was never the reason.** Every Save-as-Hypothesis button '
    + 'on the discovery lanes stamped origin_page `research-home` \u2014 the page the list is '
    + 'rendered on, not the station that produced the hit. The four lanes now stamp the '
    + 'station\u2019s route from one table, and originDest takes an address, so a card still links '
    + 'to where it was born. This corrects what this side reported earlier: measured on DEV, 8 '
    + 'of the 53 hypotheses came through those buttons, not all 53 \u2014 the other 45 are the '
    + 'loop\u2019s (35 candidate_batch_approve, 1 candidate-pool) and Copilot\u2019s (9) own saves, '
    + 'which name their path rather than a station and are right to. Rows already on file keep '
    + 'the stamp they were given, so the column counts what is saved from here on and the '
    + 'footnote says exactly that. '
    + 'Header, per Design: Ask Copilot stays (Copilot is a shell capability) carrying the census '
    + 'as its snapshot; Save as Hypothesis went, because under this scale it would add to a '
    + 'number the page reads; Daily Brief went as a menu row repeated as furniture. D10 moved '
    + 'into the lead and its footer paragraph, a fourth surface for one statement, was deleted. '
    + 'Swept: nine links \u2014 the eight built station pages and the Hypothesis Board; the three '
    + 'pages the design has and this side has not built carry none, and the dead-link gate holds '
    + 'their routes on a named list with a guard that fails the day one is routed. '
    + 'THE VERBS CAME BACK (Owner 2026-09-21): folding the lanes in had taken their readings and '
    + 'left pin / pool / Save-as-Hypothesis behind in a component nothing mounted, so a hit could '
    + 'be read where it was made and captured nowhere. They are one component now '
    + '(`DiscoveryCapture`), rendered both here and by the lane list, and the expand area keys its '
    + 'four lanes by the same constant the buttons stamp \u2014 a hit cannot be captured on one '
    + 'row and claim another. A backtest run gets none: it is already an artifact. '
    + 'Signed off by the Owner 2026-09-21.'
    + ' '
    + 'A FACE, NOT A PAGE, since 2026-09-22 (Rev 2026-09-22.2, \u00a75a.9). The design\u2019s FILES table '
    + 'has always mapped this route and /research/overview to one prototype \u2014 the census was built '
    + 'into the layer page \u2014 and this side had built them as two pages under two menu rows, which '
    + 'is the shape \u00a75a.1 swept everywhere else. The Pipeline row left the menu, the body moved '
    + 'into `PipelineCensusFace`, and both routes render the layer page with the face the route '
    + 'names. Nothing of the reading was lost \u2014 the Owner\u2019s question when the fold left '
    + '(\u300cPipeline \u9875\u9762\u91cc\u7684\u4e1a\u52a1\u4ef7\u503c\u8fd8\u662f\u9700\u8981\u4fdd\u7559\u5427\u300d) is answered by the segment: one click, or this '
    + 'same deep link. The row is menu-less on purpose, so standing on the census lights the '
    + 'Research layer row rather than a row of its own.',
  '/research/loop/harness':
    'Walked 2026-09-18 against Research Overview.dc.html (the seat-home view) at page rev 2026-09-14.1, on local DEV (:5173) \u2014 batch R1 of the Research walk. The prototype\u2019s own ruling for the seat homes is that they are NOT redesigned (\u201cstays as it is \u2014 what changed is around them\u201d): the menu must not reshuffle on arrival (the R0 seat model already follows the route), the seat must show on the page as a context tag, and Plan this rides on outputs (the Inbox side, aligned earlier). Built accordingly: the design\u2019s Context strip under the header \u2014 the L3 tag with the autopilot seat name and one sentence \u2014 with the prototype\u2019s \u201cvisiting\u201d note deliberately absent, because this side\u2019s rail follows the route and there is no visiting state to describe. The console itself (objectives, runs, leash, curate) is production\u2019s own and stays untouched, which is exactly what the prototype asks. Withdrawn 2026-09-19: the walk above leaned on the prototype ruling that the seat home is not redesigned. Package 2026-09-19.1 gives harness its own prototype — Research Autopilot Console.dc.html at Rev 2026-09-18.2: D10 badge, five-cell standing, universe reach, the leash panel, objective cards with the run and objective drawers — so that basis is gone and the W1 re-walk is against that page. Re-walked 2026-09-19 against Research Autopilot Console.dc.html (Rev 2026-09-18.2), the page’s first prototype of its own. The console the app already had was most of it — D10 badge, trust chip, context strip, standing, reach, policy templates, objective cards with runs and the pipeline drawer — which is the package’s own reading (the design catching the app, not the reverse). Added to close the walk: the leash panel mounted on the console (same component the Inbox mounts, per-objective floor vs record), the standing split to the design’s five cells (Drafts beside the calls they fold into), the per-objective Spend today cell, and the section’s closing paragraph on folding, the bill and what deletion keeps. Not drawn, with reasons: the trust chip’s dial suffix (no dial store until W4), the six-verb row on memos (the shared component is W3), the drawer’s Journal link (the page is W4). Objective and run detail keep their own routes — the drawer form is the design’s compact rendering of the same content and it does not require the route change.  Re-walked 2026-09-22 against Package 2026-09-22.3 (Rev .6), which changed two things here. The run drawer retired: a run is a surface with an identity of its own, so it opens as a tab (or a float) rather than as this page’s right-hand inspector, and `?run=` is consumed into that surface and gives the address bar back. Its S/M/L width control went with the shell — width is the surface header’s question now. And the Copilot button points at the one Thread rather than at a dock.'
    + 'Objective scope wired 2026-09-21, the third page carrying the same bug. Here no link '
    + 'needs resolving — these rows *are* the objectives — so a scope narrows the console to '
    + 'the one machine, which is the whole point of laying a scope over it. One case needed '
    + 'naming: a scope on an objective this filter does not list (archived while the console '
    + 'shows Active, or deleted) would otherwise read as “this machine has no runs”, which is a '
    + 'different claim from “it is not here”. The banner says which, and that branch was '
    + 'verified by scoping to an objective outside the active list. '
    + 'Re-walked 2026-09-21 against the prototype on the Owner’s reading that Autopilot still '
    + 'deviated, and the deviation was structural. The design draws **Runs today** as a page-'
    + 'level section across every objective, with an Objective column, its own status filter '
    + 'and the closing line about folding and archived objectives. This side had the runs only '
    + 'inside each card’s expander plus a small orphan block for runs whose objective had left '
    + 'the list — so the console could answer “this objective’s runs” and could not answer '
    + '“what ran today”, which is the question the section exists for. Built it: every run, '
    + 'folded, across objectives, the objective named in a column and opening its page; the '
    + 'run-status filter moved out of the Objectives header into this one, where the design '
    + 'has it; and the orphan block folded in, because a run whose objective was archived is '
    + 'now a row with its name on it rather than a footnote about disappearance. The card’s '
    + 'own expander stays: it answers a different question (that objective’s whole history) '
    + 'and the design puts that on the objective’s page, which this side also has. Two '
    + 'divergences named on the page rather than drawn. The Objectives filter has **two** '
    + 'states where the design has five: the backend’s OBJECTIVE_STATUSES is active/archived '
    + 'and refuses anything else with a 422, so draft, paused and retired have no column to '
    + 'enter and the header says so instead of drawing tabs nothing can reach. And New '
    + 'objective is still a form over a policy template, not the design’s three-origin panel: '
    + 'of its three, **Template** is what the dialog already does, **Fork** is buildable (copy '
    + 'a standing objective’s policy into a new one through the create call that exists) and '
    + 'is the next real piece, and **Promote** is not — it reads a hand-run history of screens '
    + 'and scans that nothing on this side records. Interaction sweep: the Objective cell '
    + 'opens that objective’s page, verified by clicking; the run-status filter and the two '
    + 'objective-state tabs both act; no page-level overflow. The re-walk read the current '
    + 'prototype, so the recorded rev moves from 2026-09-18.2 to the package’s own '
    + '2026-09-20.1 — the walk was against that file, and leaving the older stamp would '
    + 'have made an aligned page read stale the moment it was signed. '
    + 'Owner signed off 2026-09-21 on local DEV (:5173) at this rev.',
  '/research/loop/hypotheses':
    'Walked 2026-09-18 against Research Hypothesis Board.dc.html at page rev 2026-09-17.1, on local DEV (:5173) \u2014 batch R1. Rebuilt to the design\u2019s shape: header wording and the \u201cSettled record \u2192 Playbook stats\u201d link; lane chips with counts; the \u201cProposed by Copilot\u201d queue as a real panel over pending hypothesis_suggestion drafts, approved or dismissed through the draft queue (\u00a711.3) \u2014 with one wording correction against the prototype: approving records your call and writes NO hypothesis (agents.py routes the kind through the advisory pass-through branch), so the button says Approve, never the prototype\u2019s \u201cAccept \u2192 testing\u201d; the card grid with state tag, scope (first symbol or BOOK), age, title, born-on line + thesis, and a footer whose record cell reads the outcome-rule resolution \u2014 the only settled record a hypothesis stores \u2014 and whose destination link goes to the origin page when the free origin_page token names a live route, else to the backtest builder. Diverged knowingly: the lanes are the server\u2019s own states (active / validated / rejected / archived) \u2014 the design\u2019s testing \u00b7 parked lifecycle has no column, and drawing lanes no row can enter would be a lie in chip form; the design\u2019s per-hypothesis \u201c4-1 settled\u201d record and stake cells have no store (one resolution per row, no position link) and are not invented; the footer keeps the design\u2019s falsifier point but says plainly there is no falsifier field. The conviction-cap sentence is not carried \u2014 Compare and its cap do not exist here. Rev 2026-09-18.2 adds operator birth tags and the six-verb row to every card; the W1 re-walk covers the tags, the verbs land with the shared component in W3. W1 (2026-09-19): the .2 delta landed — every card footer carries the operator birth tag (hand · loop · copilot), derived from origin_page until provenance is stored (W2); the crumbs and the menu moved to Research › The Book, seat-free. The verb row waits for the shared component (W3). '
    + 'Re-walked 2026-09-20 under the interaction standard, and it found a real bug: **the '
    + 'objective scope was not read here at all.** The design scopes this page by provenance '
    + '(Vision §16.3) and the generated registry lists it among DESIGN_OBJ_WIRED, so the Lens '
    + 'tells the reader the scope applies — while the board showed every row under any scope. '
    + 'That is the worst of the three states: the shell claims a filter the page ignores. '
    + 'Measured before wiring it, 53 hypotheses on DEV: 34 carry no run_id at all (9 from the '
    + 'Copilot queue, 8 written by hand on Research home, 17 from candidate approvals) — the '
    + 'design’s “opened by hand”, which a scope legitimately hides. The other 19 carry a '
    + 'run_id, across three distinct runs, and **not one of those runs exists any more**: '
    + '/research/objective-runs returns 29 and none matches, and asked directly the API says '
    + '`run not found`. So nothing on this board can be attributed to an objective today. '
    + 'Divergence, and the reason for it: the scope is **reported, not applied**. Filtering on '
    + 'a link that resolves to nothing would empty the board for a reason about the record '
    + 'rather than about the machine, and 53 real rows would disappear behind a data gap. The '
    + 'banner names the scope, says how many are attributable (zero), splits the rest into the '
    + 'two honest reasons — opened by hand, or carrying a run that no longer resolves — and '
    + 'offers Clear. When the runs resolve, `attributable` stops being zero and the filter can '
    + 'turn on; the reading is one function, tested. Interaction sweep: every href resolves '
    + '(Playbook stats, the per-card Backtest deep link with its tab and hypothesis_id, '
    + 'Research home, Candidate Pool), the Backtest link was clicked and lands on the page '
    + 'with its parameters read, the lane chips filter and light, and Clear empties the shell '
    + 'scope. No page-level overflow at 1024. '
    + 'Banner extracted 2026-09-21 to `ObjectiveScopeBanner` when the third page grew the same '
    + 'one. It always carries three parts — the scope’s name, what the page did about it, and '
    + 'the way out — because the middle part is the one that differs, and differs honestly: '
    + 'applied on the Pool and the Console, reported with the filter off here. '
    + 'Swept again 2026-09-21: every link resolves and the Copilot draft panel is correctly '
    + 'absent — the drafts endpoint has zero pending `hypothesis_suggestion` rows on DEV, and '
    + 'the design draws that panel conditionally too. What is still owed is the verb row and '
    + 'the per-card operator/parent line, both waiting on the shared verbs component. '
    + 'Owner ruled 2026-09-21 (option B): the six-verb row is **its own piece of work, not a '
    + 'walk’s**. What each verb writes and where it lands — Explain, Challenge, Fork, Extend, '
    + 'Settle, Distill — is a product decision that has to be settled before a shared component '
    + 'can be built, and a walk that guessed at it would bake the guess into two pages at once. '
    + 'So it stays recorded as owed here rather than counted as a gap this page can close. '
    + 'Walked again 2026-09-21 beside the prototype at 1500px, and the scope reading was wrong '
    + 'because it had only looked down one road. The wiring resolved a hypothesis\u2019s objective '
    + 'through `origin_ref.run_id`, found that not one of the 19 rows carrying a run id names a '
    + 'run that still exists, concluded nothing on the board could be attributed, and so '
    + 'reported the scope without applying it. But a hypothesis promoted from a candidate also '
    + 'carries `origin_ref.candidate_id`, and the candidate carries `source_ref.objective_id` \u2014 '
    + 'which is exactly how the Candidate Pool scopes itself. Through that second hop **9 of '
    + 'the 53 resolve**, all to obj-daily-loop-stock. A link is dead only when every path to it '
    + 'is, and this one was not. The scope **filters** now, as the design does, and the lane '
    + 'counts read the scoped set so a chip never promises rows the scope has taken away; it '
    + 'falls back to reporting only when nothing at all resolves, because emptying the board '
    + 'over deleted runs would say something about the record rather than about the objective. '
    + 'The banner separates four reasons now rather than three \u2014 came from it, carried no '
    + 'provenance to follow, names a run or candidate that no longer exists, came from another '
    + 'objective. Built: the design\u2019s **Proposed by Copilot** panel, the hypothesis_suggestion '
    + 'and hypothesis_draft queue answered with Accept and Dismiss through the same mutations '
    + 'the Inbox uses. It renders only when something is waiting, as the design\u2019s own sc-if '
    + 'does, and the queue is empty in every status on DEV \u2014 so the footer names it, because a '
    + 'queue nobody can see is indistinguishable from one that does not exist. Swept: 10 links, '
    + 'the Playbook stats link and one Backtest deep link per card carrying tab, hypothesis_id '
    + 'and symbols \u2014 all three read by that page; no horizontal overflow at 1500 or 1024. '
    + 'Read against the prototype card by card after that, and the cards were the wrong shape. '
    + 'Three fixes. The state tag reads ACTIVE rather than active, as the design sets it. The '
    + 'evidence line is one sentence: the design\u2019s is about eighty-five characters, and the '
    + 'theses this side stores run to 1538 over ten sentences (median 194, first sentence alone '
    + 'about 150), so the card had been printing the whole wall behind a three-line clamp and '
    + 'cutting it mid-word \u2014 cardEvidence takes the first sentence of the salient part and the '
    + 'full thesis stays on the element\u2019s title, so nothing is lost by the cut. And the record '
    + 'row is in the design\u2019s order now \u2014 record, stake, operator, destination \u2014 where it had '
    + 'led with the operator; the record is the column a reader scans down. The stake is marked '
    + 'rather than dropped: not one of the 53 hypotheses links an opportunity, so nothing on '
    + 'this side knows what is riding on a belief. '
    + 'One correction to the entry above: the Copilot queue panel was **already built here** as '
    + 'SuggestionQueue, and the walk added a second copy of it before noticing. The duplicate '
    + 'is gone; the original gained the second kind (hypothesis_draft beside '
    + 'hypothesis_suggestion) instead. '
    + 'Owner signed off 2026-09-21 on local DEV (:5173) at this rev, with the six-verb row '
    + 'still owed \u2014 it is the last shape difference between this card and the prototype.',
  '/research/loop/candidates':
    'Walked 2026-09-18 against Research Candidate Pool.dc.html at page rev 2026-09-17.1, on local DEV (:5173) \u2014 batch R1. Built: the design\u2019s header sentence trued up (the Curator screens in \u2014 the console\u2019s own Curate action \u2014 ttl expiry screens out, you promote; \u201cAdd to Pool\u201d lives on Scan and the discovery pages, not on every Inspector) with the Decision Inbox \u2192 link; the strip over the pool \u2014 In pool, Latest batch (newest trade_date and its count), Above promote line kept as the design\u2019s sentence with no number because no promote line exists, and Pool policy stated on the real mechanism (ttl_at \u2192 expired; Promote writes a Hypothesis and the row keeps the link); an Age column from created_at, green the day a row lands and amber once its ttl is inside two days, the ttl date in the title; and the design\u2019s footnote rewritten to what the number is \u2014 Score is the loop\u2019s composite at ingest, it ranks attention and sizes nothing (D10) \u2014 because the prototype\u2019s Fit (\u201cactive hypotheses\u2019 entry conditions, weighted by settled record\u201d) is an algorithm nobody has built. Diverged knowingly: no Fit bar (the score\u2019s scale is not a percentage and a bar to an unknown scale would invent one); source tags stay neutral until the value set is worth colouring; the vehicle and thesis-sketch columns have no fields \u2014 tags, lens snapshot and T+5 vs SPY are the real columns this side has, and they stay. Kept beyond the design: the outcome summary strip, the Book column, trade-date column and the confirm-on-dismiss dialog. Rev 2026-09-18.2 makes each row a nomination artifact with an operator/parent line and the six verbs; W1 covers the operator line, the verbs W3. W1 (2026-09-19): the .2 delta landed — each row’s Source cell carries the operator chip by the design’s own rule (YOU → hand, CURATOR → loop, a screen → hand); crumbs and menu moved to The Book. The .2 prototype’s new footnote claims promote writes to the Watchlist through the proposal-card queue — the server still says otherwise (candidates.py: promote writes a hypothesis directly, no queue), so the trued sentence stays. The verb row and the per-row operator/parent line wait for the verbs component (W3). '
    + 'Objective scope wired 2026-09-21, after the same bug was found on the Hypothesis Board: '
    + 'the design lists this page in DESIGN_OBJ_WIRED and the Lens told the reader the scope '
    + 'applied here, while the pool showed every row under any scope. Here the link resolves — '
    + 'every candidate carries the objective that proposed it on `source_ref.objective_id`, 55 '
    + 'of 62 on DEV — so the scope **filters**, which is the design’s own behaviour. The banner '
    + 'says what it hid and why it was hidden: 49 of 62 came from this objective, 6 from '
    + 'another, 7 from no objective at all. Both hidden kinds are part of the answer to “what '
    + 'did THIS machine produce”, and they are different answers, so they are counted apart. '
    + 'Verified by clicking, filter and Clear both. '
    + 'Walked again 2026-09-21 under the interaction standard, and one earlier claim was '
    + 'withdrawn. The note had said the design’s Thesis-sketch column “has no field”; that was '
    + 'too strong. Every candidate carries a `lens_snapshot` — measured over 62 rows on DEV, '
    + 'path and grade on 51, stage on 50, sepa_score on 50, momentum_score on 49, an options '
    + 'lens on a handful — and that *is* the sketch in the vocabulary this side has: the '
    + 'objective’s own plan says analyze_symbol attaches “which layer(s) fired”, and this is '
    + 'what it attached. The Why column writes out only the lenses present, so a name a screen '
    + 'nominated is blank rather than carrying a sentence invented for it. Score gained the '
    + 'design’s bar, drawn **against the best score in view** rather than to 100: the composite '
    + 'has no documented ceiling (observed 0.71 to 85.2) and a bar to one would invent a scale. '
    + 'The footnote says both. Interaction sweep: Decision Inbox, each symbol’s own link and '
    + 'Promote/Dismiss all resolve; the row is not clickable, which matches the prototype — it '
    + 'has explicit actions rather than a row target. '
    + 'Full walk 2026-09-21 on the Owner’s reading that the gap was still large. Two of the '
    + 'design’s cells turned out to be buildable after all, and both had been written off. '
    + '**Curator run** replaces the strip’s “Latest batch”. Latest batch was the newest '
    + 'trade_date among the rows — a fact about the rows; the design asks when the *machine* '
    + 'last acted and what the act cost, and the two part company exactly when a run proposes '
    + 'nothing, which is when you most want to know it ran. Both halves are real: '
    + '/research/objective-runs carries started_at and, in outputs, the candidate_ids that run '
    + 'proposed; runSpend already reads the token bill for the console. The cell reads the '
    + 'newest run, what it put in, what expiry has screened out, and the cost, and keeps the '
    + 'newest batch beneath it as the smaller fact it is. **Parent** is the other: the '
    + 'prototype writes it as free text (“memo r-0918-2”), and this side has the real run on '
    + '`source_ref.run_id`, so the row links to it — through loopPipelinePath, the console’s '
    + 'own address for a run, rather than the /research/loop/runs/:id path that only redirects '
    + 'there. Verified by clicking: the pipeline drawer opens on that run. A candidate no run '
    + 'proposed has no parent rather than an invented one. What the design still draws and '
    + 'this side does not: the per-row **verb row** and the vehicle column. The verbs are a '
    + 'shared component that does not exist and are a product decision (what each of the six '
    + 'writes, and where it lands) rather than a walk’s work; the vehicle has no field. '
    + 'Everything else on the page is this side’s own and stays: the outcome strip, the Book '
    + 'column, Status, T+5 vs SPY and the confirm-on-dismiss dialog. '
    + 'Owner ruled 2026-09-21 (option B): the six-verb row is **its own piece of work, not a '
    + 'walk’s**. What each verb writes and where it lands — Explain, Challenge, Fork, Extend, '
    + 'Settle, Distill — is a product decision that has to be settled before a shared component '
    + 'can be built, and a walk that guessed at it would bake the guess into two pages at once. '
    + 'So it stays recorded as owed here rather than counted as a gap this page can close.'
    + 'Walked again 2026-09-21 beside the prototype at 1500px, and it found four things. '
    + 'The pool table sat bare on the canvas with its Status filter floating above it; the '
    + 'design puts it in a panel with the ranking rule in the header, and the filter is that '
    + 'panel\u2019s action \u2014 it decides what the panel contains, which is what an action is for. '
    + 'Second, the table laid out fixed with no column widths, so it split ten ways evenly and '
    + 'squeezed **Actions to sixteen pixels**: the page\u2019s two verbs were a pair of unlabelled '
    + '28px icons at the clipped right edge of a table that had to scroll. Widths are explicit '
    + 'now, each with max-w-none beside it because DenseTableHead carries max-w-0 and wins '
    + 'silently otherwise, and Why takes what is left since it is the only cell that wraps. '
    + 'Third, the verbs read as the design\u2019s own words, Promote and Drop, rather than as '
    + 'icons. Fourth, the width they needed came from two columns that were repeating '
    + 'themselves: Status printed the filter you had just chosen on every row (it returns '
    + 'under All), and Tags printed Source and the Why cell\u2019s data_source again \u2014 measured, '
    + '58 of the 64 tagged candidates on DEV carry *only* those two, so every one of those '
    + 'rows said both twice. candidateOwnTags drops a tag the same row already shows and keeps '
    + 'the six rows whose tags say something (iv-hot, pivot, d4-acceptance); the full list '
    + 'stays in the cell\u2019s title. The table fits its panel now with nothing clipped, and at '
    + '1024 it scrolls inside its own wrapper rather than the page. '
    + 'Fit re-measured and still absent, now with both halves named: the design ranks by how '
    + 'many of the active hypotheses\u2019 entry conditions a name satisfies, weighted by each '
    + 'hypothesis\u2019s settled record \u2014 none of the 29 active hypotheses links an opportunity, '
    + 'so no entry condition is attached to any of them, and none carries a resolution, so '
    + 'there is no settled record to weight by. A Fit percentage would be a number with '
    + 'nothing behind it, and the footnote says so. '
    + 'Read again the same day and the rows were still wrong in shape. The design gives every '
    + 'candidate a **second line** \u2014 the artifact it is, who wrote it, what it grew from \u2014 and '
    + 'this side had scattered those three: the operator chip sat in the Source cell beside a '
    + 'tag that said the same thing (harness maps to loop and to nothing else), and the parent '
    + 'run sat inside the Why cell, which is about the lenses that fired. Each was next to '
    + 'something it is not about, and the table read as a thin spreadsheet instead of the '
    + 'design\u2019s two-line blocks. The provenance line is built now and carries all three, with '
    + 'the parent as a link to the run\u2019s pipeline; Source is one tag again and Why is the '
    + 'sketch alone. The six verbs share that line in the design and are named on it as owed '
    + 'rather than drawn, per the Owner\u2019s 2026-09-21 ruling. Checked under both Open and All '
    + '\u2014 the colspan follows the Status column in and out \u2014 and the table fits its panel in '
    + 'both. Owner signed off 2026-09-21 on local DEV (:5173) at this rev.',
  '/research/journal':
    'Built from nothing 2026-09-21 against Research Journal.dc.html at rev 2026-09-19.2, on '
    + 'local DEV (:5173). The design calls it history: every artifact, whoever wrote it, with '
    + 'its branches and what it settled to, append-only. Measured before building: there is no '
    + 'artifact endpoint anywhere in the Research API, so the tree is not a store on this side '
    + '— it is a join across five, and every edge was resolved against DEV before a line was '
    + 'written. 29 objective runs; 36 of 36 candidates resolve to the run that proposed them '
    + '(source_ref.run_id); 9 of 9 candidate.hypothesis_id resolve; 9 of the 16 hypotheses that '
    + 'carry an origin_ref.candidate_id resolve inside the window and the other 7 name older '
    + 'candidates; 188 of 200 pending drafts reach a parent through payload.hypothesis_id, '
    + 'payload.run_id or scope; 114 settled outcomes join by candidate_id. That is the page. '
    + 'Built: the day scope (defaulting to the newest day that holds a run, not to today — on a '
    + 'quiet day, opening on an empty page says the machine is broken when it is only Sunday), '
    + 'the operator filter on the menu’s own axis (Autopilot unattended vs Copilot on request, '
    + 'plus hand), the trees, the Settled table and the Selected panel with real provenance. '
    + 'Marked, not dropped — and these are most of the reason to read this note: there is no '
    + 'fork record anywhere in any of the five stores, so three of the design’s five header '
    + 'readings (branches, merged, considered-not-merged) carry no number and name what is '
    + 'missing; a zero there would say the loop tried nothing rather than that nobody writes it '
    + 'down. No artifact carries a conversation id, so the provenance row for thread stays and '
    + 'reads not recorded. There are no screen versions and no reads, so those two node types '
    + 'have nothing to draw. The design’s Settled table splits Right and Wrong by which lens, '
    + 'persona or judge the outcome belongs to; the store settles a candidate against a '
    + 'benchmark and keeps no join to the evidence it cited, so the two columns become one '
    + '(Cited, which is what the nomination actually carried) and Feeds says the attribution is '
    + 'missing. That gap is the learning loop’s input, and naming it is the point. A null hit '
    + 'is kept apart from a miss: an outcome the rule has not judged is a silence, not a '
    + 'verdict against the candidate. The six-verb row is absent by the Owner’s 2026-09-21 '
    + 'ruling (option B): what each verb writes and where it lands is a product decision, and '
    + 'building a guess here would bake it into a third page — the panel says so where the row '
    + 'would be. Reach: the drafts API caps a page at 200 per status, so the day picker lists '
    + 'only the days the window reaches. The Book’s menu fold gained its fourth row the same '
    + 'hour the page landed; it has been in the design’s fold:book since the package was '
    + 'written. '
    + 'Walked again 2026-09-21 beside the prototype at 1500px, and it moved three things. '
    + 'The header tiles were the design’s five readings reordered and one of them replaced: '
    + 'the build had promoted the Inbox count to a tile of its own and dropped **merged**, '
    + 'which is a reordering of the design’s argument dressed up as an addition — the design '
    + 'writes the Inbox count as merged’s own subtitle, and it is back there, so the five '
    + 'slots and their order are the design’s again. The tree cap is the **station** now '
    + 'rather than the kind at the root, which is what makes a day scannable; the mapping is '
    + 'the loop’s own lap (objectiveLapModel’s six), and the two kinds written about a day '
    + 'rather than at a station — a digest, a playbook note — answer null and fall back to '
    + 'the kind instead of being filed under a near-enough one. The design gives each of the '
    + 'six stations a colour and this side does not: ObjectiveLap already decided how a '
    + 'station is coloured and decided differently, spending colour only on the two that '
    + 'leave the research loop, and six hues here would be a second convention for the same '
    + 'word one click away. Third, provenance is walkable, which the design asks for in one '
    + 'line through its Explain verb — *each input is a node in this Journal; click one to '
    + 'walk the chain*. A value that names another artifact selects it, a symbol opens the '
    + 'name, and a value nothing in view answers stays plain rather than becoming a link to '
    + 'nowhere. Walking takes the day with it: a parent is usually older than the artifact '
    + 'naming it — a candidate proposed on the 11th, settled on the 18th — so landing on it '
    + 'while the tree list still showed the day you came from put the answer in the right '
    + 'panel and nothing on the left. Swept at 1500 and 1024: no horizontal overflow, node '
    + 'rows select and carry the name in ?sel=, Escape clears it, and the aside’s one way '
    + 'out goes to the page that owns the artifact. '
    + 'Owner signed off 2026-09-21 on local DEV (:5173) at this rev.',
  '/research/book':
    "Built 2026-09-20 against Research Book.dc.html (Rev 2026-09-20.24), the fold's own page, "
    + 'then re-walked the same day after /risk and /portfolio, section by section. Four parallel '
    + 'children and none of them is The Book, so it gets a page rather than an alias. It answers '
    + 'what the four cannot, because every judgment on it is a cross-table one: a watchlist name '
    + 'no hypothesis is about, a candidate past its expiry, a belief with no settled position '
    + 'behind it. Measured on DEV before building: 22 watchlist names of which 4 carry a thesis, '
    + '62 candidates (2 open, 10 promoted, 7 dismissed, 43 expired), 29 hypotheses all active, '
    + 'and 0 of them carrying an opportunity id. The second pass: Census leads with the count as '
    + 'a number in the band’s own colour, says what each state is, and prints the split as tags '
    + 'rather than text. Waiting on you carries its own verdict in the header with the panel '
    + 'tinted behind it, and took the design’s five columns — Where, Scope, What is waiting, '
    + 'Reason, Age — so a row says which of the three tables it lives in instead of leaving that '
    + 'to the tag; the age ink turns amber at four days and red at eight, the design’s own '
    + 'thresholds. Four views became rows with the size of what each one holds beside it, which '
    + 'is the difference between a list of where to click and a list of what is worth clicking. '
    + 'An `as of` chip joined the header, reading the *stalest* of the three queries rather than '
    + 'the freshest: the census is a claim across all three, so it is only as current as the one '
    + 'that answered longest ago. Four honest divergences. The hypothesis lanes are the store’s '
    + 'own — active / validated / rejected / archived — not the design’s active / testing / '
    + 'parked / retired: printing the design’s words over these counts would make `parked` mean '
    + '`archived`, and those are opposite claims. The empty lanes keep their rows where the '
    + 'design filters them out, because on DEV all three settled lanes read zero and that is the '
    + 'reading — nothing has ever settled. The Journal band shows a dash with its reason rather '
    + 'than a zero, and its row in Four views does not link anywhere: there is no artifact store '
    + 'and no page, and answering a click about history with the Hypothesis Board would be worse '
    + 'than not linking. And a candidate’s waiting row says who nominated it and what the loop '
    + 'scored it, where the design prints a vehicle no column stores. Thin record currently '
    + 'catches every active hypothesis, which is the broken lineage bridge (REQUEST R5) reading '
    + 'through; the panel names that cause above its rows rather than leaving 29 identical '
    + 'sentences to be read as 29 problems. '
    + 'Owner review 2026-09-20: the layout aligned but the page did not behave like one — '
    + 'a ticker was text. Three interactions landed after it. The whole stuck row opens the '
    + 'table it lives in, which is the prototype’s own behaviour and the only thing that makes '
    + 'a five-column row worth reading before you click it; keyboard reaches it the way the '
    + 'ledger’s rows do. The Scope cell is its own destination — the ticker opens that name on '
    + 'Symbol through withSymbolParam, so the way from a stuck row to the evidence behind it '
    + 'is a click rather than retyping it; a belief about the whole book reads BOOK and is not '
    + 'a link, decided from a symbol field rather than by matching that word. And the two '
    + 'places Journal appears say on hover why they go nowhere instead of looking like links '
    + 'that silently do nothing. No deep link into the three tables: none of them reads a row '
    + 'parameter, and a link carrying one they ignore is the failure this pass was fixing.',
}
